### ISSUE TITLE
No thumbnail when mutagen is installed

### ISSUE THREAD

**Issue by iamtherobin** [axcore/tartube#352] opened 2021-11-20 00:33 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 7

### What version of Tartube are you using?
v2.3.332

### What happens when you run Tartube from a terminal window?
When downloading some podcast videos using -x command in download options to get audio only, I am seeing this error:

ERROR: module mutagen was not found. Please install using `python -m pip install mutagen`

The download completes just fine and the video thumbnail shows up as well despite this error. There is a yellow triangle icon on the video, however. Both a .png and .webm thumbnail are downloaded.

If I open mingw and type 'pip install mutagen' it will install the package and then following that, I can download the audio without seeing the error and no yellow triangle on the video. However, once I do that, the video thumbnail no longer shows up in tartube. Only a .webm thumbnail is downloaded in this case.

For now I uninstalled mutagen. What exactly is mutagen used for?

**Comment by axcore** [comment] 2021-11-20 06:45
>What exactly is mutagen used for?

[No idea](https://pypi.org/project/mutagen/), but I would guess it's probably used by FFmpeg.

I'm away from my desk until January and can't do any testing, but if the you're getting the downloads you want, I would suggest telling Tartube to ignore that particular error. Edit > System preferences... > Windows > Websites, and add **module mutagen was not found** to the large box.

**Comment by iamtherobin** [comment] 2022-04-06 12:53
Using latest tartube, I don't get an embed thumbnail error at all when using -x but I am also not using --embed-thumbnail switch. I am currently not seeing any errors about mutagen at this time. I am not even certain if it is still installed since I uninstalled and reinstalled latest tartube to fix ffmpeg and I did not turn on the install yt-dlp dependency options.

**Comment by axcore** [comment] 2022-04-06 16:19
Ok, then I will risk closing the issue, because I suspect that yt-dlp has been updated, fixing the cause of your issue.

If you get the same problem again, feel free to re-open this issue.

**Closed by axcore** 2022-04-06 16:19 UTC
Labels: bug
