### ISSUE TITLE
error accessing system preferences

### ISSUE THREAD

**Issue by 7uxifer** [axcore/tartube#594] opened 2023-10-23 16:44 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Fedora 38

### What version of Tartube are you using?
2.4.412

I'm using yt-dlp, so I try to go into the settings to set the path ( Edit | system preferences...), and I get an error.  Interestingly the 'copy selected' button in the Errors/Warnings section does nothing, so I am writing the error by hand

Uncaught exception:
Type: <class 'ValueError'>
Value: 'ytdl_update_default_path' is not in list
Traceback:  File /usr/lib/python3.11/site-packages/tartube/mainapp.py", line 25539
...
...
File "/usr/lib/python3.11/site-packages/tartube/config.py", line 26779 in setup_downloader_paths_tab self.app_obj.ytdl_update_list.index(

**Comment by axcore** [comment] 2023-10-24 06:18
Do you know where tartube's config file is? You don't specify which of the million different installation methods you used, so I can't guess it; the file is called `settings.json`

If you can find it, open it in a text editor and show me the list called `ytdl_update_list`. This is what mine looks like:

![updatelist2](https://github.com/axcore/tartube/assets/37951926/852046a5-f00e-48a9-a04c-7fd47bcf8775)

**Comment by axcore** [comment] 2023-10-24 15:52
Great, I think I understand what the problem is, though I'll do some more testing to make sure.

If you need to re-install Tartube between now and the next release, make sure you're not using the .rpm marked STRICT, as that's the broken one.

Re-opening so I don't forget to do it.

**Comment by axcore** [comment] 2023-11-21 08:18
Fixed in v2.4.429.

**Closed by axcore** 2023-11-21 08:18 UTC
Labels: bug
