### ISSUE TITLE
PNG thumbnails deleted and not embeded

### ISSUE THREAD

**Issue by adenry** [axcore/tartube#626] opened 2024-03-26 19:17 UTC
OS: Windows 10
Tartube version: 2.5.0

As the title says, when I download videos that have PNG thumbnails, I can see the thumbnail successfully downloaded, but then just before it'd be embeded into the video, it gets deleted (and, naturally, not embeded).

When I pass the EXACT same command (copy-paste from Tartube Output) to a separate instance of yt-dlp.exe that I downloaded directly from the yt-dlp github, this issue does not happen, the thumbnail is downloaded and embeded into the video.

Here's Tartube's output:

```
python3 -X utf8 ..\..\..\mingw64\bin\yt-dlp.exe --newline -i --hls-prefer-native --write-description --write-info-json --cookies C:/Users/user/Downloads/Tartube/cookies.txt --write-thumbnail --write-sub --all-subs --embed-subs --embed-thumbnail --add-metadata --fixup warn --windows-filenames --ignore-no-formats-error --output "D:/test/%(title)s.%(ext)s" https://www.starwars.com/video/trailer-the-bad-batch
[Disney] Extracting URL: https://www.starwars.com/video/trailer-the-bad-batch
[Disney] trailer-the-bad-batch: Downloading webpage
[Disney] 5beb54f010f3bebd6b4f2a72: Downloading m3u8 information
WARNING: [Disney] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] 5beb54f010f3bebd6b4f2a72: Downloading subtitles: en_us
[info] 5beb54f010f3bebd6b4f2a72: Downloading 1 format(s): mp4-4007
[info] Writing video description to: D:/test/Official Trailer - Star Wars： The Bad Batch.description
[info] Writing video subtitles to: D:/test/Official Trailer - Star Wars： The Bad Batch.en_us.srt
[download] Destination: D:/test/Official Trailer - Star Wars： The Bad Batch.en_us.srt
[download] 100% of    2.53KiB in 00:00:00 at 158.97KiB/s
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: D:/test/Official Trailer - Star Wars： The Bad Batch.png
[info] Writing video metadata as JSON to: D:/test/Official Trailer - Star Wars： The Bad Batch.info.json
[download] Destination: D:/test/Official Trailer - Star Wars： The Bad Batch.mp4
[download] 100% of   59.39MiB in 00:00:05 at 10.27MiB/s
[EmbedSubtitle] Embedding subtitles in "D:/test/Official Trailer - Star Wars： The Bad Batch.mp4"
[Metadata] Adding metadata to "D:/test/Official Trailer - Star Wars： The Bad Batch.mp4"
WARNING: Skipping embedding the thumbnail because the file is missing.
```

I tried disabling webp to jpg convesion in System preferences (as suggested here https://github.com/axcore/tartube/issues/461 ) but that didn't help. Also, the "...but don't delete the original thumbnails" option is enabled.

Here are links to this video and a couple others like that that have this issue (all have PNG thumbnails):
https://www.starwars.com/video/trailer-the-bad-batch
https://www.starwars.com/video/season-2-official-trailer-star-wars-the-bad-batch
https://www.starwars.com/video/extraction-star-wars-the-bad-batch

Here are links to videos that have JPEG thumbnails instead, and don't have this issue:
https://www.starwars.com/video/sizzle-the-bad-batch
https://www.starwars.com/video/featurette-meet-the-the-bad-batch

One last thing - when I open one of those PNG thumnails with IrfanView, it says it is actually not a PNG, but a JPG. Maybe that's part of the issue?

**Comment by axcore** [comment] 2024-09-30 08:23
Many apologies, it seems that I didn't notice this issue at any time during the six months since you posted it.

I tried the videos; yt-dlp is currently unable to download any of them (even without trying to embed thumbnails):

```
yt-dlp https://www.starwars.com/video/featurette-meet-the-the-bad-batch
[Disney] Extracting URL: https://www.starwars.com/video/featurette-meet-the-the-bad-batch
[Disney] featurette-meet-the-the-bad-batch: Downloading webpage
ERROR: [Disney] Unable to download webpage: The read operation timed out (caused by TransportError('The read operation timed out'))

```

Are you noticing the same problem with a video that yt-dlp _can_ download?

**Comment by adenry** [comment] 2024-10-01 17:23
Strange, they downloaded fine back when I posted about this issue.

Anyway, here's another link to the first video, this one can be downloaded, and the PNG issue that I described originally is still present:
https://video.disney.com/watch/star-wars-the-bad-batch-official-trailer-disney-5bec30e18976cebd6b4f2a72

**Comment by axcore** [comment] 2024-10-14 15:41
Apologies, I was unable to reproduce your issue. Try my test for yourself, and see if you get the same results:

1. Click Edit > General download options, and in the **Additional download options** box, add this text:

--write-description --write-info-json --write-thumbnail --write-sub --all-subs --embed-subs --embed-thumbnail --add-metadata --fixup warn --windows-filenames --ignore-no-formats-error

Click OK to close the window, then download the video. According to VLC, the thumbnail is embedded:


1. Click Edit > General download options, and in the **Additional download options** box, remove **--embed-thumbnail**.

Click OK to close the window, then re-download the video. According to VLC, the thumbnail is not embedded:

**Comment by adenry** [comment] 2024-10-15 09:25
@axcore

Thanks for your help. I think I was able to track down the issue now.

I am using Classic Mode, and I made a custom download options for it. I exported it and I will try to attach the file here.
[starwars.com download options.json](https://github.com/user-attachments/files/17375705/starwars.com.download.options.json)

The issue is that the thumbnail gets deleted before being embedded. So to fix it, I just went to the dropdown menu in Classic Mode > Edit download options > Files > Keep - and here I enabled "Keep the thumbnail file after the download has finished". After enabling that option, embedding the thumbnail works. However, I have to manually delete the thumbnail file afterwards, which is not a big issue for me.
Still, I believe Tartube deletes the PNG thumbnail file before embedding it, whereas it should delete it after that, obviously. But I have no idea why it only does it with PNGs and not with JPEGs.

If you want, see if you can recreate the issue using Classic Mode and the attached download options file.

**Comment by axcore** [comment] 2024-10-21 11:55
I have done a lot of testing on this problem. The results are quite confusing. For example, I imported your download options, then tried downloading the video. When the video is in Tartube's **Unsorted videos** folder, the thumbnail is successfully embedded, but if I create a **Test** folder and download the video there, the thumbnail is _not_ embedded.

I decided to try delaying the deletion of the thumbnail (and other metadata files) until the end of the download operation. It seems to be working, but you can try it for yourself. If it solves your problem I will roll out the fix for all users.

The updated code is only available here on Github. You can update your installation by downloading the new source code files, replacing the old ones [as described here](https://github.com/axcore/tartube?tab=readme-ov-file#update-tartube-on-ms-windows).

**Comment by axcore** [comment] 2024-10-21 11:58
>So my question here is - what can I do to be able to use  --impersonate chrome with Tartube?

Click **Edit > General download options**. In the **Additional download options** box, add anything you like, for example` --impersonate chrome`

![impersonate](https://github.com/user-attachments/assets/4cd19448-3ce1-48c9-bc50-3911e56c1276)

**Comment by adenry** [comment] 2024-10-22 15:24
> Click **Edit > General download options**. In the **Additional download options** box, add anything you like, for example` --impersonate chrome`


That is exactly what I did, only I am using my custom download settings for Classic mode, so I added it in the Additional download options there. And like I said, it does not work, I get this error in Tartube's output:

> yt_dlp.utils.YoutubeDLError: Impersonate target "chrome" is not available. Use --list-impersonate-targets to see available targets. You may be missing dependencies required to support this target.

And like I said, when I run Tartube's yt-dlp.exe directly from console with --list-impersonate-targets, it says none of them are "available":

> Chrome - curl_cffi (not available)
> Edge - curl_cffi (not available)
> Safari - curl_cffi (not available)

It's like somehow the impersonate targets are not installed or something?

**Comment by adenry** [comment] 2024-10-22 15:29
> I have done a lot of testing on this problem. The results are quite confusing. For example, I imported your download options, then tried downloading the video. When the video is in Tartube's **Unsorted videos** folder, the thumbnail is successfully embedded, but if I create a **Test** folder and download the video there, the thumbnail is _not_ embedded.
> 
> I decided to try delaying the deletion of the thumbnail (and other metadata files) until the end of the download operation. It seems to be working, but you can try it for yourself. If it solves your problem I will roll out the fix for all users.
> 
> The updated code is only available here on Github. You can update your installation by downloading the new source code files, replacing the old ones [as described here](https://github.com/axcore/tartube?tab=readme-ov-file#update-tartube-on-ms-windows).

I downloaded the code and replaced the file as per your instructions. The version is now v2.5.047. Unfortunately, the issue still persists, the thumbnail is still not being embedded (`WARNING: Skipping embedding the thumbnail because the file is missing.`) unless I turn on the option to keep the thumbnail file.

I am not sure that this issue is worth your valuable time, it is a minor issue that has a workaround with the option to keep the thumbnail file.

**Comment by axcore** [comment] 2024-10-28 15:49
>So my question here is - what can I do to be able to use  --impersonate chrome with Tartube?

Apparently you need to install [curl-cffi](https://pypi.org/project/curl-cffi/). I tried installing it on Windows 10, but it would not install using any of the methods described [in the documentation](https://pypi.org/project/curl-cffi/). 

You could try it yourself (if  you really wanted to) by opening the MINGW64 terminal as [described here](https://github.com/axcore/tartube?tab=readme-ov-file#71-tartube-wont-installwont-rundoesnt-work), but I suspect it won't work for you either.

The answer to your question, then, is "I don't know".

**Comment by axcore** [comment] 2024-10-28 15:53
>it is a minor issue that has a workaround with the option to keep the thumbnail file.

In case you didn't already know, you can remove many thumbnails quickly. For example, to remove all the thumbnails from a channel, right-click it and select **Channel actions > Tidy up channel.** In the new window, select **Delete all thumbnail files**, and then click OK to start.

That won't work for videos downloaded in the Classic Mode tab.

**Comment by axcore** [comment] 2024-10-28 16:12
> Unfortunately, the issue still persists, the thumbnail is still not being embedded

If you are not already sick of the issue, it would be useful to know the exact circumstances in which the thumbnail is not embedded, so I can try to reproduce it. Like, for example, "In the Videos tab I created a new folder/I  used the Unsorted Videos folder, there I added the video <url>, and I used the same download options as before, and here is a output visible in the Output tab"

**Comment by adenry** [comment] 2024-10-31 15:28
> > So my question here is - what can I do to be able to use  --impersonate chrome with Tartube?
> 
> Apparently you need to install [curl-cffi](https://pypi.org/project/curl-cffi/). I tried installing it on Windows 10, but it would not install using any of the methods described [in the documentation](https://pypi.org/project/curl-cffi/).
> 
> You could try it yourself (if you really wanted to) by opening the MINGW64 terminal as [described here](https://github.com/axcore/tartube?tab=readme-ov-file#71-tartube-wont-installwont-rundoesnt-work), but I suspect it won't work for you either.
> 
> The answer to your question, then, is "I don't know".

That's a bummer. Seems I will have to use pure yt-dlp to download. If you find another workaround, please let me know, I'd really prefer to use Tartube if possible.


> If you are not already sick of the issue, it would be useful to know the exact circumstances in which the thumbnail is not embedded, so I can try to reproduce it. Like, for example, "In the Videos tab I created a new folder/I used the Unsorted Videos folder, there I added the video , and I used the same download options as before, and here is a output visible in the Output tab"

Sure, I will help any way I can. 
I am always using Classic Mode. I am using the custom download options that I exported for you a few posts above, I am downloading to C:\Users\user\Downloads\Tartube\tests
I paste the URL (https://video.disney.com/watch/star-wars-the-bad-batch-official-trailer-disney-5bec30e18976cebd6b4f2a72), click Add URLs, click Download All. I can see the thumbnail is successfully downloaded, but it just doesn't get embedded before being deleted. Here's the output:

```
python3 -X utf8 ..\..\..\mingw64\bin\yt-dlp.exe --newline -i --hls-prefer-native --write-description --write-info-json --cookies C:/Users/user/Downloads/Tartube/cookies.txt --write-thumbnail --write-sub --all-subs --embed-subs --embed-thumbnail --add-metadata --fixup warn --windows-filenames --no-cookies --ignore-no-formats-error --output "C:/Users/user/Downloads/Tartube/tests/[%(upload_date>%Y-%m-%d)s] %(title)s [SWC] [%(resolution)s].%(ext)s" https://video.disney.com/watch/star-wars-the-bad-batch-official-trailer-disney-5bec30e18976cebd6b4f2a72
[Disney] 5bec30e18976cebd6b4f2a72: Downloading webpage
[Disney] Extracting URL: https://video.disney.com/watch/star-wars-the-bad-batch-official-trailer-disney-5bec30e18976cebd6b4f2a72
[Disney] 5bec30e18976cebd6b4f2a72: Downloading m3u8 information
WARNING: [Disney] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] 5bec30e18976cebd6b4f2a72: Downloading subtitles: en_us
[info] 5bec30e18976cebd6b4f2a72: Downloading 1 format(s): mp4-3910
[info] Writing video description to: C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].description
[info] Writing video subtitles to: C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].en_us.srt
[download] Destination: C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].en_us.srt
[download] 100% of    2.53KiB in 00:00:00 at 2.54KiB/s
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].png
[info] Writing video metadata as JSON to: C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].info.json
[download] Destination: C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].mp4
[download] 100% of   57.94MiB in 00:00:06 at 9.14MiB/s
[EmbedSubtitle] Embedding subtitles in "C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].mp4"
[Metadata] Adding metadata to "C:/Users/user/Downloads/Tartube/tests/[2021-03-30] Star Wars： The Bad Batch ｜ Official Trailer ｜ Disney+ [SWC] [1920x1080].mp4"
WARNING: Skipping embedding the thumbnail because the file is missing.

```

**Comment by axcore** [comment] 2024-11-26 16:10
This _should_ be fixed in v2.5.059 (which is a full release). I had quite a time tracking down the problem; but your Star Wars video now downloads with embedded thumbnails in both the Videos tab and the Classic Mode tab.

**Comment by adenry** [comment] 2024-11-26 23:51
@axcore 
Yes, it works now! The thumbnail is successfully embedded and then deleted.
Sorry if this took too much of your time. But thank you for your hard work, I appreciate it!

PS: Any chance some new workaround became available so we can use "--impersonate chrome" in Tartube? Should I open a new issue about it and close this one? That's the last problem I need to find a solution for.

**Comment by axcore** [comment] 2024-12-05 11:26
curl_cffi still cannot be installed on the current version of [MSYS2](https://www.msys2.org/) (used by Tartube versions v2.5.059 and v2.5.062). 

Some people have reported similar issues (see [here](https://github.com/lexiforest/curl_cffi/issues/121) and [here](https://github.com/lexiforest/curl_cffi/issues/344)), but for different operating systems; there are apparently no solutions available for Windows/MSYS2 users.

If you need the functionality enough, it might be necessary to install a copy of Linux, either directly to your hard drive, or using virtualisation software like [Virtualbox](https://www.virtualbox.org/).

**Comment by adenry** [comment] 2024-12-05 15:15
I guess I'll have to use pure yt-dlp in this case. Unfortunate, but easier than installing Linux on a vm just for this.

Hopefully they will fix it in the future and perhaps then it could be added to Tartube.

Thank you for your help, axcore!

**Closed** 2024-12-05 15:29 UTC
Labels: bug
