### ISSUE TITLE
yt-dlp: error: no such option: --prefer-insecure

### ISSUE THREAD

**Issue by sempiterne** [axcore/tartube#364] opened 2021-12-03 10:28 UTC
![Screenshot-9](https://user-images.githubusercontent.com/47304660/144586638-a0fcf7d2-e7fe-428a-81c3-b0af3ee134dc.png)

MX Linux 19 xfce

Trying yt-dlp in terminal with "--prefer-insecure" option and video processing normally
Execution Tartube`s internal function "Test yt-dlp" is processing fine. 
Dont know why Tartube says error on that option and wonder how to ignore it.

**Comment by axcore** [comment] 2021-12-03 17:14
It's a bug caused by a typo in my code.

The workaround is to click **Edit > General download options...**, then in the new window see the box **Extra command line options**, and enter **--prefer-insecure** there.

Then, in the **Advanced > Workaroun** tab, de-select the option **Use an unencrypted connection to retrieve information about videos**.
 
![insecure](https://user-images.githubusercontent.com/37951926/144644431-7e8493af-e3e9-4cc1-a268-12cc94887799.png)

**Comment by sempiterne** [comment] 2021-12-15 12:27
> It's a bug caused by a typo in my code.
> 
> The workaround is to click **Edit > General download options...**, then in the new window see the box **Extra command line options**, and enter **--prefer-insecure** there.
> 
> Then, in the **Advanced > Workaroun** tab, de-select the option **Use an unencrypted connection to retrieve information about videos**.
> 
> ![insecure](https://user-images.githubusercontent.com/37951926/144644431-7e8493af-e3e9-4cc1-a268-12cc94887799.png)

Your advice workins as well ! Appreciate ur reply dude ! Cheers from UA 👍😁
BTW, a week later i compiled Tartube from the source and didnt have that issue, everything works 🤷‍♂️

**Comment by axcore** [comment] 2022-03-08 17:44
Fixed in v2.3.393.

**Closed by axcore** 2022-03-08 17:44 UTC
