### ISSUE TITLE
How to check if a video is unavailable?

### ISSUE THREAD

**Issue by seldron333** [axcore/tartube#530] opened 2023-04-03 11:49 UTC
Is there a way for tartube to warn me if a video I have downloaded was deleted or privated?

**Comment by axcore** [comment] 2023-04-07 06:51
Perhaps this will help you:

https://github.com/axcore/tartube#625-detecting-missing-videos

**Comment by seldron333** [comment] 2023-04-07 20:43
it only detects it if you select it undividually and click download, with check all, download all or custom download all it doesn't do anything

**Comment by axcore** [comment] 2023-04-08 07:39
A quick test suggests the function is not working as intended, I will do some full testing as soon as I have the chance.

**Comment by axcore** [comment] 2023-04-12 12:28
I have done some more testing, but I can't reproduce any problems.

I created a channel, then I artificially inserted a fake video into that channel, marked as already downloaded. Then I checked the whole channel; the fake video was detected, and placed in the red 'Missing Videos' folder. 

However, a fake video that is _not_ marked as downloaded is not detected. 

Can you describe the exact circumstances in which a missing video is detected only when you select it individually? Show me its URL, perhaps?

**Comment by seldron333** [comment] 2023-04-15 13:45
I added and downloaded with "download all" a youtube channel, and then privated a video

**Comment by axcore** [comment] 2023-11-21 08:35
Closed for inactivity.

**Closed by axcore** 2023-11-21 08:35 UTC
Labels: question
