### ISSUE TITLE
I have use the program several times and all worked great until two weeks ago. Than I had to run the setup again (came up when I started the program). First comes a question about "Install and update downloader". That gives operation finished. But never able to get through the "Install FFmpeg". Just says error. Have try it multi times. Any tips what to do?

### ISSUE THREAD

**Issue by baleroller** [axcore/tartube#550] opened 2023-05-29 07:40 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

### What version of Tartube are you using?
In Tartube's main window, click Help > About

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

**Comment by axcore** [comment] 2023-05-31 12:22
I can't offer any advice, because you didn't answer of the questions above.

Make sure you are using the most recent version of Tartube (v2.4.370.

**Comment by baleroller** [comment] 2023-05-31 16:08
I have try on both Windows 10 and 11 with exactly same error.

I can't open the program but the installation file is - install-tartube-2.4.370-64bit

**Comment by axcore** [comment] 2023-06-01 13:39
Sometimes the FFmpeg installation breaks permanently; you can try deleting the Tartube installation folder, then re-installing from scratch.

**Comment by baleroller** [comment] 2023-06-01 17:44
![Error](https://github.com/axcore/tartube/assets/134917749/0d04039d-2ee3-455d-8072-626d9fe1f4a0)

I hope this will work, I have try to attach the screenshot on the error. It is the same error on both Windows versions 10 and 11.

https://prnt.sc/23CY24bHHHmQ    If the above link doesn't work.

**Comment by axcore** [comment] 2023-06-01 18:19
Yes, it looks a lot like a corrupted installation. The quickest way out of the hole is to delete the Tartube installation directory, then re-install from scratch.

**Comment by WilmoSND** [comment] 2023-06-02 02:28
I've had this happen a few times recently. mine will fail with:
```
checking package integrity...
error: failed to commit transaction (invalid or corrupted package)
error: mingw-w64-x86_64-libvorbis: signature from "David Macek
<david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-libvorbis-1.3.7-1-any.pkg.tar.zst
is corrupted (invalid or corrupted package (PGP signature)).
```

editing pacman.conf from issue #371 solves it, though it is not the ideal solution.

**Comment by axcore** [comment] 2023-06-08 12:31
Should be fixed in v2.4.386.

**Closed by axcore** 2023-06-08 12:31 UTC
Labels: bug

**Comment by SashimiAct** [comment] 2023-10-16 00:21
Attempting to install FFmpeg during setup of v2.4.386 on Windows once again results in it failing.
```
checking package integrity...
error: failed to commit transaction (invalid or corrupted package)
error: mingw-w64-x86_64-libvorbis: signature from "David Macek
<david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-libvorbis-1.3.7-1-any.pkg.tar.zst
is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
Errors occurred, no packages were upgraded.
Update operation finished
Installation failed
```

**Comment by axcore** [comment] 2023-10-16 13:14
Use the current release of Tartube, not ancient ones.

**Comment by SashimiAct** [comment] 2023-10-16 20:00
v2.4.386 is the version currently listed as "current version" on the Sourceforge website:
https://tartube.sourceforge.io/#downloads
I'd recommend updating the links on the website if you don't want people accidentally downloading older versions.

**Comment by axcore** [comment] 2023-10-17 09:47
I checked sourceforge, the correct files are marked as the "current versions". Though I can see that half of downloaders are getting v2.4.386, so clearly you are not the only person seeing the wrong settings.

![correctlyset](https://github.com/axcore/tartube/assets/37951926/3ccf5933-473d-4290-b1ab-07546854d536)

Not sure what the problem is, when I have time i'll try deleting the v2.4.386 files and then re-uploading them, perhaps that will reset everything.
