### ISSUE TITLE
Incorrect new videos count

### ISSUE THREAD

**Issue by ethankcvds** [axcore/tartube#169] opened 2020-10-07 21:03 UTC
After removing some video files that I downloaded from tartube the file count gets messed up for new videos it shows 9/8.  The only option that fixes the issue is to start a new database.

**Comment by ethankcvds** [comment] 2020-10-07 21:05
Image showing new videos showing 0/-1.

![tartube negative videos](https://user-images.githubusercontent.com/35079277/95387699-1a6c1a00-08bf-11eb-8aa9-40ef1b38dfdc.png)

**Comment by axcore** [comment] 2020-10-08 05:39
Thanks for the bug report. It would be very helpful, if you could specify the exact process that creates the broken database.

**Comment by ethankcvds** [comment] 2020-10-14 23:00
That's just it I can't remember what I did to cause it. The only thing I can think of that I did Is removed the video files from the download folder and not directly from within tartube.

**Comment by axcore** [comment] 2020-10-15 05:53
No problem, I will code something to intercept that error.

**Comment by axcore** [comment] 2020-10-22 15:51
Fixed in v2.2.046. (This new release can be downloaded from git and pypi now; a full release will follow in a few days).

I could not find the cause of the error. But:

1. It is now impossible for the video count to go below 0
2. The database integrity check now checks that all video counts are correct, and fixes them if not.  Click **Edit > System preferences... > Filesystem > DB errors**, and click the **Check DB** button)

**Closed by axcore** 2020-10-22 15:51 UTC
