### ISSUE TITLE
Error when installing FFmpeg

### ISSUE THREAD

**Issue by Loljaey** [axcore/tartube#444] opened 2022-07-22 20:38 UTC
Everytime Tartube tries to install FFmpeg and is checking the package integrity, it gives me the following Error:

> checking package integrity...
> error: mingw-w64-x86_64-lz4: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
> :: File /var/cache/pacman/pkg/mingw-w64-x86_64-lz4-1.9.3-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> error: mingw-w64-x86_64-libvorbis: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
> :: File /var/cache/pacman/pkg/mingw-w64-x86_64-libvorbis-1.3.7-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n]
> error: mingw-w64-x86_64-ffms2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
> :: File /var/cache/pacman/pkg/mingw-w64-x86_64-ffms2-2.40-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n]
> error: failed to commit transaction (invalid or corrupted package)
> Do you want to delete it? [Y/n]
> Errors occurred, no packages were upgraded.
> Update operation finished

I tried disabling my AV but it didnt work. Is there anything i can do about it?

**Comment by boydfields** [comment] 2022-07-26 10:45
I'm having the exact same issue.

**Comment by mitro0609** [comment] 2022-07-29 00:37
Same failure here

**Comment by axcore** [comment] 2022-07-29 13:26
Duplicate of #371, so have a look at my comments there.

There will be a new release this weekend that fixes the issue.

**Closed by axcore** 2022-07-29 13:26 UTC
