### ISSUE TITLE
Not responding; increasing memory allocation?

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#157] opened 2020-09-11 12:36 UTC
When working with tartube in some places, such as the new videos tab tartube will freeze up. I'm wondering why this is? It only uses 2GB of ram, but I'm wondering if that's a hard limit or just something that happens? I'm wondering if I can increase the amount of RAM allocation for tartube?

**Comment by axcore** [comment] 2020-09-11 12:58
I am seeing the same thing on my laptop.

**Comment by axcore** [comment] 2020-09-15 06:16
On my laptop, the freeze is caused by the Tartube icon in the system tray. You can try disabling it:

**Edit > System preferences... > Windows > System tray**, and deselect **Show icon in system tray**

**Comment by axcore** [comment] 2020-09-30 15:18
Contrary to what I said above, I now think that the freeze was caused when clicking the video's**YouTube** label. The call to open the system's web browser seemed to be faulty.

I have not been able to reproduce the problem for over a week now, and I did not change the code, so I think some other library has been fixed. If you still experience this issue, make sure you've updated the system software.

(I will tentatively close the issue, but feel free to re-open it, if you need to.)

**Closed by axcore** 2020-09-30 15:18 UTC
Labels: bug
