### ISSUE TITLE
FFmpeg failing to download

### ISSUE THREAD

**Issue by MisterVideosoEx** [axcore/tartube#382] opened 2022-02-11 21:48 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.3.332

### What happens when you run Tartube from a terminal window?
Same result + no error message (however when trying to go to the website which also doesn't work, it gave the error "Couldn't export handle, unsupported windowing system")

**Comment by axcore** [comment] 2022-02-12 12:13
Duplicate of https://github.com/axcore/tartube/issues/371. You can try v2.3.367 which was released today.

**Closed by axcore** 2022-02-12 12:13 UTC
Labels: bug
