### ISSUE TITLE
Delete container fails when dialogues are turned off

### ISSUE THREAD

**Issue by Shanto** [axcore/tartube#495] opened 2023-01-14 14:23 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.4.221

### What happens when you run Tartube from a terminal window?
Nothing interesting.

### If your bug report is "I can't download this video", please provide a link to the video
Not applicable.

### Problem
Delete channel/folder (containers) fails **silently** when dialogs are turned off. This happens because the DialogManager [terminates earlier and the callback is never executed](https://github.com/axcore/tartube/blob/027247ceecc831cc3d8b17cd73fec88b324cd5d6/tartube/dialogue.py#L117). I turned off dialogs because I don't want to be notified frequently each time after downloads are completed. This resulted in breaking this delete feature with no visible feedback (e.g. in log/output tab). Possible fix is either "assume yes" and execute the callback when dialogues are turned off, or log it and let the user know that dialogues must be enabled for delete to work.

**Comment by axcore** [comment] 2023-01-17 15:37
You are talking about **Edit > System preferences > Windows > Dialogues > Temporary disable message dialogue windows...**, right?

![dialogue](https://user-images.githubusercontent.com/37951926/212940764-d1bc4dda-d9cf-4900-bb98-122b0897a470.png)

If so, it's not a bug, the code is working correctly; when Tartube is run from a terminal, the dialogue is visible there.

![dialogue2](https://user-images.githubusercontent.com/37951926/212941353-8ef7581c-4350-49ff-ab42-3b0e3be2a096.png)

This option exists because dialogue windows can cause a freeze on [Virtualbox](https://www.virtualbox.org/) that is unrelated to the problem I'm testing. So, I need a way to disable all dialogue windows.

**Comment by axcore** [comment] 2023-01-17 15:38
> I turned off dialogs because I don't want to be notified frequently each time after downloads are completed. 

This message can be disabled separately: **Edit > System preferences > Operations > Actions > Don't notify the user at the end of an operation**.

**Comment by axcore** [comment] 2023-01-17 16:05
I have updated the README to mention this function. I have also updated **Windows > Dialogue** tab to tell the user to check the **Operations > Actions** tab too. The changes will be in the next release.

**Comment by axcore** [comment] 2023-02-26 12:47
Closing for inactivity, feel free to re-open if the comments above are not helpful.

**Closed by axcore** 2023-02-26 12:47 UTC
Labels: bug
