### ISSUE TITLE
Redownloading videos is broken when an ytdl-archive.txt file is used

### ISSUE THREAD

**Issue by tsk-2222** [axcore/tartube#613] opened 2024-01-13 10:57 UTC
Windows 10,  Tartube V2.5.0

Bug: When a video is requested to be re-downloaded, the video and it's associated files are first deleted from the folder but then tartube queries the ytdl-archive.txt file and will not actually re-download the video.  Manually deleting the video's line in the ytdl-archive.txt file resolves the issue.

To reproduce:  
  turn on ytdl-archive.txt:  Edit-System preferences-Operations-Archive
  download this video (or any video):  https://www.youtube.com/watch?v=xvFZjo5PgG0
  Right click on the video and click re-download

**Comment by axcore** [comment] 2024-01-13 16:41
Confirmed.

**Comment by axcore** [comment] 2024-01-23 13:59
Fixed in v2.5.007. The new code is uploaded only to PyPI and Github. Windows users can update their existing installation by downloading the new source code from here, and using it to replace the old source code, as [described here](https://tartube.sourceforge.io/#update-tartube-on-ms-windows).

A short explanation:

Until v2.3.534, Tartube used to ignore the archive file when re-downloading. 

Unfortunately, there is a problem: in the Classic Mode tab, Tartube doesn't know if a URL represents a video or a whole channel. If you try to download a big channel, but interrupt the download before it's finished, then a re-download will continue where you left off, downloading the remaining videos. In that situation, you definitely _do_ want to use the archive file.

Because Tartube doesn't know if a URL is a video or a channel, I added a button at the bottom of the Classic Mode tab. Users can enable or disable the button as required.

My notes for v2.3.534 don't explain why the re-downloads in the Videos tab were also changed, but I have reverted the change, so they should be working as expected now.

**Closed by axcore** 2024-01-23 13:59 UTC
Labels: bug
