### ISSUE TITLE
tartube downloads all kind of junks

### ISSUE THREAD

**Issue by beew** [axcore/tartube#295] opened 2021-05-30 04:38 UTC
I tried to test tartube by downloading a video and extract the audio but instead of just the.mp3 file I want I got in addition  a .json file, a .jpeg file and a .description file in the download folder. Is this the intended behaviour? 

tartube-2.3.110, Ubuntu 20.04 and I ran tartube out of its source folder without installation and use the classic interface.

I can easily accomplish what I want with command line
```
youtube-dl --extract-audio --audio-format mp3 <URL>

```

But I am setting this up for a friend who prefers a simple GUI.

Note: Also it seems that I am unable to change tartube's download folder without a restart.

**Comment by axcore** [comment] 2021-05-30 06:33
Tartube is first and foremost an archive tool, so you get more than the just the raw video.

In the Classic Mode tab, click the menu button in the top right corner, then select **Edit download options > Files > Keep files**. (The Videos and Classic Mode tabs use different download options, see [here](https://github.com/axcore/tartube#download-options) for an explanation.)

I'm not clear what you mean by download folder: do you mean the one specified in the Classic Mode tab? If so, can you tell me the exact steps you were taking that lead to the bug?

**Comment by axcore** [comment] 2021-05-30 06:38
I just tested that, and it's not working as intended.

In the Classic Mode tab, click the menu button in the top right corner, then select **Edit download options > Files > Keep files**. If you haved deselected all the checkboxes, the extra files should not be retained (but they are).

A workaround is to click the **Write/move files** tab, and deselect all the checkboxes there too.

**Comment by axcore** [comment] 2021-05-30 06:40
When you say "tartube's download folder", which one do you mean? The one in the Classic Mode tab, or the one in **File > Database preferences...**?

I just tested the one in the Classic Mode tab, and it seems to be working as intended. Can you describe exactly what process you're using to change the folder?

**Comment by beew** [comment] 2021-05-30 19:22
Hi, by "tartube's download folder" I mean the "Destination" tab in classic mode. Thanks.

**Comment by beew** [comment] 2021-05-30 23:18
Hi, deselecting everything in the Write/move files tab works. I am wondering if it is a common use case to want to download these files, maybe these functions should be just removed or unchecked by default?

**Comment by axcore** [comment] 2021-05-31 05:47
> I am wondering if it is a common use case to want to download these files

Yes, they contain useful information. By default, they are downloaded, scanned, and then deleted. But for some reason the Classic Mode tab isn't deleting them correctly.

**Comment by axcore** [comment] 2021-07-09 15:45
Your problems are fixed in v2.3.203. There will be a full release later this month, or the updated code can be downloaded now from github.

**Closed by axcore** 2021-07-09 15:45 UTC
Labels: bug
