### ISSUE TITLE
Fatal error in launcher: U

### ISSUE THREAD

**Issue by RetroAbstract** [axcore/tartube#484] opened 2022-12-17 20:37 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

Windows 10 Pro 2H22

### What version of Tartube are you using?
In Tartube's main window, click Help > About

Version v2.4.093

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

**What shows in terminal when following the steps above & checking a video url:** 

/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42:
Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py:585: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gtk.Dialog.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py:585: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gtk.Dialog.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py:585: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gtk.Dialog.run(self, *args, **kwargs)
/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py:585: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gtk.Dialog.run(self, *args, **kwargs)

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

This bug applies to any and all videos.

Additional info:

"Fatal error in launcher: U" tends to appear when Tartube is moved from the directory the database was created in. 

For example if I extracted tartube portable to the desktop, create a database, use it for a while, then move the tartube folder to a new directory, Fatal error in launcher: U happens and I have to download/extract a fresh copy of Tartube, create a new database and reconfigure all the settings for it to work again.

**Comment by axcore** [comment] 2022-12-19 08:18
1. Download the portable installer, tartube-2.4.165-64bit-portable.zip
2. Extract it on your desktop, creating a folder called **tartube-24.165-64bit-portable**
3. Immediately inside that folder is a folder called **tartube**
4. Start Tartube, install yt-dlp, download some videos
5. Move the folder **tartube** to a new location, for example to the Downloads folder
6. Start Tartube

Is that what you are doing? You are not trying to move the folder tartube-24.165-64bit-portable/tartube/home/user/tartube, right?

**Comment by RetroAbstract** [comment] 2022-12-19 13:27
> 1. Download the portable installer, tartube-2.4.165-64bit-portable.zip
> 
>     2. Extract it on your desktop, creating a folder called **tartube-24.165-64bit-portable**
> 
>     3. Immediately inside that folder is a folder called **tartube**
> 
>     4. Start Tartube, install yt-dlp, download some videos
> 
>     5. Move the folder **tartube** to a new location, for example to the Downloads folder
> 
>     6. Start Tartube
> 
> 
> Is that what you are doing? You are not trying to move the folder **tartube-24.165-64bit-portable/tartube/home/user/tartube**, right?

Correct, Fatal error in launcher: U happens when I move the **entire tartube folder** that was extracted when downloading the zip. not the sub folder tartube-24.165-64bit-portable/tartube/home/user/tartube.

**Comment by axcore** [comment] 2022-12-19 14:01
Sorry, I don't know how to fix this. I tested these steps and I could not reproduce your problem.

[This thread](https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using) suggests it's a python installation issue, but I don't know how to resolve that.

**Comment by RetroAbstract** [comment] 2022-12-19 15:29
> Sorry, I don't know how to fix this. I tested these steps and I could not reproduce your problem.
> 
> [This thread](https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using) suggests it's a python installation issue, but I don't know how to resolve that.

I see. Thanks for that thread link.

Just tested with the latest tartube portable build and sure enough, Fatal error in launcher: U happens after the following:

1. Download tartube portable build
2. Extract zip to location A
3. Go through the initial tartube launch steps (installing yt-dlp, ffmpeg...)
4. Move entire previously extracted tartube folder from location A to location B
5. Check a video
6. Fatal error in launcher: U

**Comment by axcore** [comment] 2024-01-03 08:05
Fixed in v2.5.0. 

If you move the portable Tartube folder to a new location on your filesystem, you will need to reinstall yt-dlp. This can be done from Tartube's main menu. (It didn't work before, but now it does.)

Other components (such as FFmpeg) do not need to be reinstalled.

If you see the 'Fatal error in launcher: U' message, you should also see a Tartube message reminding you to update yt-dlp.

**Closed by axcore** 2024-01-03 08:05 UTC
Labels: bug
