### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by legrostdg** [axcore/tartube#17] opened 2019-08-13 11:09 UTC
I started packaging tartube for Debian. Here is the repo (WIP) https://salsa.debian.org/felix-guest/tartube

I would need at least #14 to be fixed before submitting the package. #16 also seems pretty important and #15 would be nice.

**Comment by axcore** [comment] 2019-08-26 14:28
@legrostdg, is there anything else you need? I'm going to release v1.2 this weekend and, after that, I'll be away from my desk for a few weeks.

**Comment by legrostdg** [comment] 2020-02-11 20:38
Sorry, I lost interest and never finished the packaging. I guess I'd like something simpler than tartube: just a youtube-dl frontend, that gets an url, some options (codec, quality, sound only, ...) and a local directory or filename. The packaging repo is still there if someone wants to finish it.

**Comment by nodiscc** [comment] 2020-02-11 22:42
I am interested in picking up the packaging work. I maintain Debian packages for personal use but I wish we could make tartube packages suited to official Debian repos for the next release. ping @axcore feel free to reopen this.

ping anyone interested in co-maintaining the Debian package

**Comment by axcore** [comment] 2020-02-12 08:08
@legrostdg By the way, "just dump everything into a single directory" is now available. The procedure would be...

Edit > System preferences > Operations > URL flexibility > Download multiple videos into the containing folder
Create a folder with the 'Add a new folder' button
Click the 'Add new video(s)' button
Copy and paste as many URLs as you like - videos, channels, playlists
Click the 'Download all' button
All videos are downloaded into the single folder

**Comment by axcore** [comment] 2020-02-12 08:13
>I am interested in picking up the packaging work

@nodisc, if you mean, "produce a .DEB package that works", I can handle that, but if you mean "produce a .DEB package and then persuade the debian maintainers to add it to their repos" then I know nothing about how that's done.

A package for the repos would have to use ../tartube/tartube_debian as the executable, because we've already removed some stuff that is definitely unacceptable for the repos.

**Comment by legrostdg** [comment] 2020-02-12 13:35
@nodiscc you can clone https://salsa.debian.org/felix-guest/tartube/
The packaging is almost done. I think there just was something with the icon path configuration.

@axcore Thanks, I won't use it myself, as I'm more cli-oriented :-). But I would like to have a very simple youtube-dl gui for other users in Debian. It means having this kind of configuration by default, as these users won't change it by themselves.

**Comment by axcore** [comment] 2020-02-12 14:32
@legrostdg Doesn't [youtube-dl-gui](https://mrs0m30n3.github.io/youtube-dl-gui/) do exactly what you want?

**Comment by legrostdg** [comment] 2020-02-12 17:53
Exactly, and I first started the packaging https://github.com/MrS0m30n3/youtube-dl-gui/issues/21 Unfortunately, not supporting python3 is now a blocker to enter Debian https://github.com/MrS0m30n3/youtube-dl-gui/issues/289

**Comment by axcore** [comment] 2020-02-12 21:19
If that's the only stumbling block, it would not be a lot of work to update youtube-dl-gui for python3. A lot of the code was re-used in Tartube, so most of the work is already done.

**Comment by legrostdg** [comment] 2020-02-14 10:18
Probably... But it seems like upstream abandoned the project :(.

**Comment by axcore** [comment] 2020-02-14 10:29
@legrostdg I'm going to do it myself, in a few days.

**Comment by axcore** [comment] 2020-02-29 14:06
I have created DEB and RPM packages for Tartube. They seem to be working properly. They can be [downloaded from here](https://sourceforge.net/projects/tartube/files/v2.0.0/)

I have changed the environment variables used to create these packages. 

Use TARTUBE_PKG=1 to create an ordinary DEB/RPM package. 

Use TARTUBE_PKG_STRICT to create a DEB/RPM package, in which youtube-dl updates are disabled. (This replaces the old TARTUBE_DEBIAN environment variable).

**Comment by nodiscc** [comment] 2020-02-29 21:29
I think you could attach the packages to https://github.com/axcore/tartube/releases if you don't want to split hosting of files to sourceforge.

I just ran `lintian` on your packages and they almost check all the boses:

```
 $ lintian python3-tartube_2.0.0.deb 
W: python3-tartube: new-package-should-close-itp-bug
E: python3-tartube: no-copyright-file
W: python3-tartube: description-starts-with-leading-spaces
W: python3-tartube: extended-description-contains-empty-paragraph
W: python3-tartube: binary-without-manpage usr/bin/tartube
```

**Comment by axcore** [comment] 2020-03-01 08:05
> python3-tartube: no-copyright-file

Upload to PyPI fails if any licence or README.rst file are included. This bug has not been fixed during the last five years, so I don't have a great expectation that it will be fixed soon.

**Comment by axcore** [comment] 2020-03-03 14:05
@nodiscc v2.0.006 removes all of the lintian errors, except for `new-package-should-close-itp-bug`.

**Comment by nodiscc** [comment] 2020-03-08 22:36
By running `TARTUBE_PKG_STRICT=1 python3 setup.py build`, you get a set of files in `build/lib/tartube/`:

```
	build/lib/tartube/__init__.py
	build/lib/tartube/config.py
	build/lib/tartube/dialogue.py
	build/lib/tartube/downloads.py
	build/lib/tartube/files.py
	build/lib/tartube/formats.py
	build/lib/tartube/info.py
	build/lib/tartube/mainapp.py
	build/lib/tartube/mainwin.py
	build/lib/tartube/media.py
	build/lib/tartube/options.py
	build/lib/tartube/refresh.py
	build/lib/tartube/testing.py
	build/lib/tartube/tidy.py
	build/lib/tartube/updates.py
	build/lib/tartube/utils.py
	build/lib/tartube/xdg_tartube.py
```

I guess the next step is to automate creation of binary `deb\`rpm` packages. Until now I guess you were doing it manually with `dpkg-deb` or similar before uploading? Or is there some step I'm missing to build a deb package?

**Comment by axcore** [comment] 2020-03-09 07:55
The procedure I used to create the `python3-tartube_2.0.0-STRICT.deb` file, on a fresh install of Debian, was this:

```
su
apt install git build-essential python3-setuptools python3-pip python3-all dh-python
apt-get install python3-stdeb fakeroot python-all
exit
pip3 install requests
```

[extract the .tar.gz]
[move stdeb.cfg from ../tartube/pack into the directory above]
```
cd Downloads/tartube
TARTUBE_PKG_STRICT=1 python3 setup.py sdist
su
TARTUBE_PKG_STRICT=1 python3 setup.py --command-packages=stdeb.command bdist_deb
exit
lintian deb_dist/python3-tartube*deb
```

**Comment by dark-penguin** [comment] 2020-04-27 16:38
The dependencies in the package are not enough. (I downloaded the package by the link in the "main page" - meaning, README.rst).

- Install the package, do `apt-get install -f`, and try running it:
ModuleNotFoundError: No module named 'gi'
- Install python3-gi (apparently, it's a runtime dependency, not a build-dep as specified in the package)
ValueError: Namespace Gtk not available

Now I don't know what else to install. `apt-cache search python3 gtk` returns very little, and nothing about GTK3.

(I'm on Debian Buster with MATE. To check for dependencies, try running it in a container with nothing installed. If it does not run, then you've missed something. I'm not running anything on my system until I try it in Docker first.)

**Comment by dark-penguin** [comment] 2020-05-03 08:55
I've confirmed this on a Debian LiveCD (Debian Buster MATE amd64).
```
Traceback (most recent call last):
  File "/usr/bin/tartube", line 40, in <module>
    import mainapp
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 61, in <module>
    import config
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 37, in <module>
    import mainwin
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 40, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```
Some other dependency missing?
I remember it working on an Ubuntu LiveCD (Eoan, I think, but maybe Focal), but not on Debian Buster.

**Comment by axcore** [comment] 2020-05-03 09:04
@dark-penguin, I'll look into this as soon as I have finished other things.

**Comment by axcore** [comment] 2020-05-07 08:20
@dark-penguin, I was not able to reproduce your errors on Debian. (In fact, I was not even able to get the package managers working on Debian, but that's another story).

I released v2.1.0 today. It explicitly names gi as a dependency; this might resolve your problem when installing from PyPI, or when using the DEB and RPM packages.

**Comment by dark-penguin** [comment] 2020-05-07 08:50
The easiest way to reproduce it would be a Debian LiveCD (debian-live-10.3.0-amd64-mate.iso). Specifically MATE! If you download the DEB and install it, it gives this error.

If you use Docker, then it's even easier (and it reproduces on anything, because the default Docker images have very little stuff preinstalled - that's why I test dependencies this way).

I've tried installing everything I could think of, including something-gi, but it didn't help. Which package exactly is "gi" ?

By the way, I don't see anything like this in the latest DEB. Here is its debian/control:
```
Package: python3-tartube
Source: tartube
Version: 2.1.0-1
Architecture: all
Maintainer: A S Lewis <aslewis@cpan.org>
Installed-Size: 3957
Depends: python3-feedparser, python3-requests, python3:any
Section: python
Priority: optional
Homepage: https://tartube.sourceforge.io
Description: GUI front-end for youtube-dl
 .
 Tartube is a GUI front-end for youtube-dl, partly based on youtube-dl-gui
 and written in Python 3 / Gtk 3.
```

**Comment by axcore** [comment] 2020-05-07 09:02
Then I don't know what to suggest. The Python `setup.py` file contains this line:

`install_requires=['feedparser', 'gi', 'playsound', 'requests'],`

As we can see, the DEB packager picks up the need for feedparser and requests, but not gi or playsound.

`Depends: python3-feedparser, python3-requests, python3:any`

**Comment by axcore** [comment] 2020-05-07 10:14
>OK, so the problem is that some Debian packaging tools don't automatically pick up all dependencies.

Yes, this must be the case. This is what I do to produce the Tartube DEB package, on a clean install of Debian (with Cinnamon):

```
su
apt install git build-essential python3-setuptools python3-pip python3-all dh-python
apt-get install python3-stdeb fakeroot python-all
exit
pip3 install feedparser playsound requests
cd Downloads/tartube
TARTUBE_PKG=1 python3 setup.py sdist
su
TARTUBE_PKG=1 python3 setup.py --command-packages=stdeb.command bdist_deb
exit
lintian deb_dist/python3-tartube*deb
```

**Comment by nodiscc** [comment] 2022-11-07 21:55
The Request for Packaging to get Tartube included in official Debian repositories can be found here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934681.

**Comment by axcore** [comment] 2022-11-22 13:27
That request was added by the same person who opened this issue.

**Closed** 2022-11-25 05:34 UTC
Labels: help wanted
