### ISSUE TITLE
Mojibake in classic mode and output tabs

### ISSUE THREAD

**Issue by kwon0408** [axcore/tartube#304] opened 2021-06-21 16:47 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10 21H1, UI language is Korean for both Windows and Tartube.

### What version of Tartube are you using?
v2.3.110

### What happens when you run Tartube from a terminal window?
Some strings in Hangul (and maybe other scripts) becomes mojibake in the GUI. Names of the saved files are OK.
![image](https://user-images.githubusercontent.com/31509569/122798547-ad3ccf80-d2fb-11eb-878a-cf076ab60b9f.png)
![image](https://user-images.githubusercontent.com/31509569/122798564-b332b080-d2fb-11eb-95bb-88ee6209cd86.png)

Nothing changes when I run this via `mingw64` terminal.

**Comment by axcore** [comment] 2021-07-09 15:52
Seems to be a duplicate of #153 and #251. Sorry, but I don't know how to fix the problem.

**Comment by axcore** [comment] 2021-08-03 09:39
Closed this and several related issues, replacing it with a single issue: https://github.com/axcore/tartube/issues/320

**Closed by axcore** 2021-08-03 09:39 UTC
Labels: bug
