### ISSUE TITLE
'Is a livestream' enabled seems to break livestream downloads

### ISSUE THREAD

**Issue by xecus922** [axcore/tartube#643] opened 2024-07-16 04:41 UTC
_OS: Windows 10 Pro 64-bit (10.0, Build 19045)
Version: Tartube version 2.5.0

This is related to https://github.com/axcore/tartube/issues/553

After months of headaches and frustration, trying to figure out why livestream downloads were broken all of a sudden, trying every suggested fix from the above page I've realized that it's the 'is a livestream' toggle being enabled on my classic window that has been the issue strangely enough. 

I can't remember if I always had this enabled but I figured it only makes sense to keep it enabled and would've never expected for it to be the issue. 

But whenever I have this enabled the downloads come out as 'livestream_X' and it's a broken video that doesn't load. 

This is what my livestream options look like in case you're wondering. Feel free to share any suggestions on them if anything looks crazy, I'm not the most familiar with the available options: 
![2024-07-16_00-38-18](https://github.com/user-attachments/assets/5cb4641e-dd6e-4899-bbf4-a9af00693475)

But disabling this 'is a livestream' option fixed livestream downloads immediately.

**Comment by axcore** [comment] 2024-07-22 07:17
I tested this and immediately noticed a bunch of Python errors. They are all fixed in v2.5.024, and the "is a livestream" button seems to be working as intended.

The new code is only uploaded to Github/Pypi. There will be a full release in a few days, I'm just waiting for some other updates.

**Closed by axcore** 2024-07-22 07:17 UTC
Labels: bug
