### ISSUE TITLE
Tartube commands aren't compatiable with zsh

### ISSUE THREAD

**Issue by MM4096** [axcore/tartube#654] opened 2024-09-28 07:51 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Linux (Ubuntu 24)

### What version of Tartube are you using?
2.5.0

### If your bug report is "I can't download this video", please provide a link to the video
The commands run by Tartube (yt-dlp commands) do not work on a zsh shell, resulting in the following output: 
```
yt-dlp --newline -i --hls-prefer-native --cookies /home/coding/Documents/Tartube/cookies.txt -f bestvideo[height<=?720]+bestaudio/best[height<=?720] --output /home/coding/Documents/Tartube/Downloads/%(title)s.%(ext)s https://www.youtube.com/watch\?v\=cJ-pQaNCDAQ

zsh: bad pattern: bestvideo[height
```
I assume this is because `zsh` has `?` be a matching character, and isn't well escaped.

**Comment by axcore** [comment] 2024-09-30 08:00
I can reproduce this using yt-dlp alone. Namely, in zsh:

```
yt-dlp -f bestvideo[height<=?720]+bestaudio/best[height<=?720] https://www.youtube.com/watch\?v\=cJ-pQaNCDAQ
zsh: bad pattern: bestvideo[height
```

I can't reproduce it using when running Tartube from zsh. Specifically, on Linux Mint I open the Gnome terminal, and type

```
zsh
python3 tartube/tartube
```

Then in Tartube's window, I click  **Edit > General download options**, and add this to the **Additional download options** box:

`-f bestvideo[height<=?720]+bestaudio/best[height<=?720]
`
In this case, the download of [your video](https://www.youtube.com/watch\?v\=cJ-pQaNCDAQ) is successful. Perhaps you can spot what I haven't done that would reproduce the problem.

**Comment by axcore** [comment] 2024-09-30 08:04
For yt-dlp, the problem can be resolved by enclosing the download option in quotes, i.e.

-f "bestvideo[height<=?720]+bestaudio/best[height<=?720]"

In Tartube, there is a complication: because of some Python and/or shell behaviour I don't understand, enclosing each download option within quotes creates more problems than it solves. 

You could _try_ using the quotes in **Edit > General download options**, but I can't predict what effect it will have:


`-f "bestvideo[height<=?720]+bestaudio/best[height<=?720]"`

**Comment by MM4096** [comment] 2024-10-01 04:44
I also can't reproduce this by running `bash` then `zsh` to emulate coming from a bash terminal. However, running `tartube` straight from a `zsh` terminal (and a `zsh` environment) results in this quote problem.

**Comment by axcore** [comment] 2024-10-21 10:34
Sorry for such a long day in replying. Today I tested Tartube running in zsh. This time I'm sure it really is zsh, and not bash:

![zshell](https://github.com/user-attachments/assets/560dd12d-93aa-4701-9f92-be3e694cbb34)

The [video from your original post](https://www.youtube.com/watch\?v\=cJ-pQaNCDAQ) is no longer available on YouTube. I tried several other brand new videos, but could reproduce your error using them. Do you have a video whose link is still available?

**Comment by MM4096** [comment] 2024-10-21 22:29
As it appears, I had an earlier version of Tartube installed (2.5.0-1). 
Updating to the latest version has fixed this problem.

**Closed** 2024-10-21 22:29 UTC
Labels: bug
