### ISSUE TITLE
AttributeError during setup

### ISSUE THREAD

**Issue by iloveitalready** [axcore/tartube#325] opened 2021-08-07 07:30 UTC
Tartube setup seemed to be missing some GUI elements, so I ran it from the terminal. The window appears but when I click next there is a blank window and this is what it says in the terminal:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tartube/wizwin.py", line 507, in on_button_next_clicked
    self.setup_page()
  File "/usr/local/lib/python3.8/dist-packages/tartube/wizwin.py", line 248, in setup_page
    method()
  File "/usr/local/lib/python3.8/dist-packages/tartube/wizwin.py", line 811, in setup_db_page
    msg = utils.tidy_up_long_string(
AttributeError: module 'utils' has no attribute 'tidy_up_long_string
```

The GUI window: [https://i.imgur.com/wjyTLLX.png](https://i.imgur.com/wjyTLLX.png)

I'm on Linux Mint 20.2 Cinnamon.

**Comment by axcore** [comment] 2021-08-08 06:03
I don't know how to explain this error. The attribute definitely exists; I have checked my working directory, and also checked the downloads from github and sourceforge.

Can you please tell me precisely which link you used to download the code. 

Perhaps you could also check the **../tartube/utils.py** file, and tell me how many lines it contains. The .**tidy_up_long_string()** is near the end of the file, so perhaps the end part has gone missing.

**Comment by ykhurshid** [comment] 2021-11-03 12:38
Hi, I'm having an identical error here. On my utils.py file, the total number of lines is 3472 and the tidy_up_long_string function is defined in line 3101. 

I installed tartube through the AUR (i use arch btw. . .)

I will now uninstall it and attempt to see if this problem goes away by installing through pip instead.

**Comment by axcore** [comment] 2021-11-03 16:21
I can't reproduce the error, so I'm not sure what to suggest. If you like, you could try just [running the source code](https://github.com/axcore/tartube#5310-run-without-installing), since installation is not actually required.

**Comment by ykhurshid** [comment] 2021-11-04 12:51
Seems to work just fine when I run it from source so I'm chocking this to the package on pip and the AUR being botched.

**Comment by axcore** [comment] 2022-04-07 12:26
Today I tested the AUR package (v2.3.367) on Manjaro. Not sure how everyone else is installing Tartube, but I did this:

```
sudo pacman -Sy base-devel git
git clone https://aur.archlinux.org/tartube.git
cd tartube
makepkg -is
```

This failed because of missing dependencies, but succeeded after I installed those dependencies separately.

![manjaro](https://user-images.githubusercontent.com/37951926/162197828-f21e6838-a328-4b63-a036-89802c67daee.png)

I'm not familiar with Manjaro, Arch or AUR packages in general, so I can't say why the dependencies were not installed automatically, or if that was the cause of your problem.

Anyway, following the successful test and due to the age of this issue, I will now close it. Feel free to start a new issue specifically for Manjaro if you need to.

**Closed by axcore** 2022-04-07 12:26 UTC
