### ISSUE TITLE
Tartube does not play well with unicode character title Win7

### ISSUE THREAD

**Issue by iamtherobin** [axcore/tartube#251] opened 2021-01-20 23:44 UTC
Windows 7 x64
Python 3.8.6
Tartube 2.3.085

Trying to download a video with a unicode character works when checking the channel but once I actually download the video, Tartube does not recognize it anymore because of the filename. If I enable force ASCII filenames, it works as expected and recognizes the file. The worst part about this is that if the youtube-dl archive is enabled, the archive file it will add the video into the archive preventing it from being downloaded again until the archive entry is removed and the channel is re-checked.

Video is recognized in simulated download when checking the channel and shows up correctly in the channel list:
<a href="https://imgur.com/G6GQRV6"><img src="https://i.imgur.com/G6GQRV6.png" title="source: imgur.com" /></a>
Video successfully downloads missing the unicode character in the log:
<a href="https://imgur.com/1fr2TXE"><img src="https://i.imgur.com/1fr2TXE.png" title="source: imgur.com" /></a>
Filename as downloaded on the system:
<a href="https://imgur.com/8KY5ZLD"><img src="https://i.imgur.com/8KY5ZLD.png" title="source: imgur.com" /></a>
Tartube does not recognize the video is downloaded in the list:
<a href="https://imgur.com/EiKgoyR"><img src="https://i.imgur.com/EiKgoyR.png" title="source: imgur.com" /></a>

The next two just show the expected result using forced ASCII option:
<a href="https://imgur.com/NOSpqxT"><img src="https://i.imgur.com/NOSpqxT.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/eBuCOvm"><img src="https://i.imgur.com/eBuCOvm.png" title="source: imgur.com" /></a>

**Comment by axcore** [comment] 2021-01-25 13:39
After extensive testing, I have concluded that youtube-dl itself is broken. Compare the output when checking a CRP video (green line) and downloading the same video (red line). When checking, youtube-dl correctly writes the unicode characters `\ud83d\udd34`. When downloading, the unicode characters are not written at all.

![unicodetest2](https://user-images.githubusercontent.com/37951926/105712960-757b5880-5f12-11eb-87a5-c075b1fe7469.png)

The difference between checking a video, and downloading it, is the youtube-dl option `--dump-json`. When this command-line option is added, Tartube receives the video's metadata in JSON format. Tartube takes the filename directly from the metadata (the green text). When the command-line option is not added, the metadata is not received directly (the red text).

I would suggest asking for a fix at the [youtube-dl page](https://github.com/ytdl-org/youtube-dl/issues), but the probability that anyone will do anything is close to zero.

**Comment by iamtherobin** [comment] 2021-01-26 00:59
Well that is too bad. I will just stick to ASCII then.

Taking a peak at youtube-dl issues, it looks like the issue has already been raised. I am thinking of bringing to youtube-dlc's attention but I have a feeling they would be relying on youtube-dl to fix this.

**Comment by axcore** [comment] 2021-01-26 09:25
The problem is described concisely [here](https://discuss.python.org/t/choosing-correct-encoding-for-subprocess-popen/3388/2). Unfortunately, the solutions suggested there don't work with Tartube installations, probably because they are running under MSYS2, rather than on Windows directly.

In tartube/downloads.py, at about line 4110, the solution should be this:

```
        try:
            self.child_process = subprocess.Popen(
                cmd_list,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                preexec_fn=preexec,
                startupinfo=info,
                encoding="mbcs",
            )
```

...with the addition being the `encoding="mbcs"` line, but that doesn't work, and neither do values like `utf-8`, `utf-16` or `cp1252`.

By the way, in case you have any Linux boxes sitting around, this is an MS Windows-only problem; Coach RP downloads work flawlessly on my Linux Mint box.

**Comment by axcore** [comment] 2021-02-28 14:39
The MS Windows installer for v2.3.110 contains some extra stuff for locales. It might possibly solve your problem. Perhaps you can test it, and tell me what happens.

**Comment by iamtherobin** [comment] 2021-02-28 21:26
Just tested using youtube-dl and the results are the same. I cannot test youtube-dlp because the update is failing and the existing version I had from over a month ago does not work.

**Comment by axcore** [comment] 2021-08-03 09:39
Closed this and several related issues, replacing it with a single issue: https://github.com/axcore/tartube/issues/320

**Closed by axcore** 2021-08-03 09:39 UTC
