### ISSUE TITLE
ffmpeg installation failed

### ISSUE THREAD

**Issue by drknss89** [axcore/tartube#443] opened 2022-07-04 23:22 UTC
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

Windows 11 Home

### What version of Tartube are you using?
In Tartube's main window, click Help > About

v2.4.077

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

Starting update operation, installing FFmpeg
pacman -S mingw-w64-x86_64-ffmpeg --noconfirm
resolving dependencies...
looking for conflicting packages...

Packages (96) mingw-w64-x86_64-SDL2-2.0.20-1  mingw-w64-x86_64-aom-3.3.0-2  mingw-w64-x86_64-asciidoc-10.1.4-1  mingw-w64-x86_64-boost-1.78.0-3  mingw-w64-x86_64-celt-0.11.3-4  mingw-w64-x86_64-ceres-solver-2.0.0-3  mingw-w64-x86_64-cppunit-1.15.1-2  mingw-w64-x86_64-crt-git-9.0.0.6448.b03cbfb95-1  mingw-w64-x86_64-curl-7.82.0-1  mingw-w64-x86_64-dav1d-0.9.2-1  mingw-w64-x86_64-docbook-xml-1~4.5-2  mingw-w64-x86_64-docbook-xsl-1.79.2-7  mingw-w64-x86_64-eigen3-3.4.0-1  mingw-w64-x86_64-ffms2-2.40-1  mingw-w64-x86_64-freeglut-3.2.2-1  mingw-w64-x86_64-freeimage-3.18.0-7  mingw-w64-x86_64-frei0r-plugins-1.7.0-3  mingw-w64-x86_64-gavl-1.4.0-1  mingw-w64-x86_64-gcc-libgfortran-11.2.0-10  mingw-w64-x86_64-gflags-2.2.2-4  mingw-w64-x86_64-glog-0.5.0-3  mingw-w64-x86_64-glsl-optimizer-git-1~r66913.d78c3d2f24-1  mingw-w64-x86_64-gnutls-3.7.4-1  mingw-w64-x86_64-gsm-1.0.19-1  mingw-w64-x86_64-hdf5-1.12.1-2  mingw-w64-x86_64-headers-git-9.0.0.6448.b03cbfb95-1  mingw-w64-x86_64-hlsl2glsl-git-1~r848.14dd189-1  mingw-w64-x86_64-icu-69.1-1  mingw-w64-x86_64-ilmbase-2.5.7-6  mingw-w64-x86_64-intel-tbb-1~2020.3-1  mingw-w64-x86_64-jansson-2.14-2  mingw-w64-x86_64-jasper-2.0.33-1  mingw-w64-x86_64-jemalloc-5.2.1-2  mingw-w64-x86_64-jxrlib-1.1-3  mingw-w64-x86_64-l-smash-2.14.5-2  mingw-w64-x86_64-lame-3.100-1  mingw-w64-x86_64-lcms2-2.13.1-2  mingw-w64-x86_64-leptonica-1.81.1-1  mingw-w64-x86_64-libaec-1.0.6-2  mingw-w64-x86_64-libarchive-3.6.0-1  mingw-w64-x86_64-libass-0.15.2-3  mingw-w64-x86_64-libb2-0.98.1-2  mingw-w64-x86_64-libbluray-1.3.0-2  mingw-w64-x86_64-libcaca-0.99.beta20-1  mingw-w64-x86_64-libexif-0.6.24-2  mingw-w64-x86_64-libgcrypt-1.10.0-1  mingw-w64-x86_64-libgme-0.6.3-3  mingw-w64-x86_64-libgpg-error-1.44-1  mingw-w64-x86_64-libidn2-2.3.1-1  mingw-w64-x86_64-libmfx-1.25-1  mingw-w64-x86_64-libmodplug-0.8.9.0-4  mingw-w64-x86_64-libmysofa-1.2.1-1  mingw-w64-x86_64-libogg-1.3.5-1  mingw-w64-x86_64-libpsl-0.21.1-4  mingw-w64-x86_64-libraw-0.20.2-5  mingw-w64-x86_64-libsoxr-0.1.3-3  mingw-w64-x86_64-libssh-0.9.6-2  mingw-w64-x86_64-libtheora-1.1.1-6  mingw-w64-x86_64-libunistring-0.9.10-4  mingw-w64-x86_64-libunwind-13.0.1-1  mingw-w64-x86_64-libvorbis-1.3.7-1  mingw-w64-x86_64-libvpx-1.11.0-2  mingw-w64-x86_64-libxslt-1.1.35-1  mingw-w64-x86_64-lz4-1.9.3-1  mingw-w64-x86_64-metis-5.1.0-4  mingw-w64-x86_64-nettle-3.7.3-3  mingw-w64-x86_64-nghttp2-1.47.0-1  mingw-w64-x86_64-ogre3d-1.12.6-4  mingw-w64-x86_64-openal-1.21.1-4  mingw-w64-x86_64-openblas-0.3.20-1  mingw-w64-x86_64-opencore-amr-0.1.5-1  mingw-w64-x86_64-opencv-4.5.2-4  mingw-w64-x86_64-openexr-2.5.7-6  mingw-w64-x86_64-openjpeg2-2.4.0-3  mingw-w64-x86_64-opus-1.3.1-4  mingw-w64-x86_64-protobuf-3.16.0-3  mingw-w64-x86_64-pugixml-1.12-2  mingw-w64-x86_64-rav1e-0.4.1-1  mingw-w64-x86_64-rtmpdump-git-r514.c5f04a5-4  mingw-w64-x86_64-speex-1.2.0-1  mingw-w64-x86_64-speexdsp-1.2.0-1  mingw-w64-x86_64-srt-1.4.4-1  mingw-w64-x86_64-suitesparse-5.10.1-2  mingw-w64-x86_64-svt-av1-0.9.1-1  mingw-w64-x86_64-tesseract-ocr-5.1.0-1  mingw-w64-x86_64-tinyxml-2.6.2-5  mingw-w64-x86_64-vid.stab-1.1-1  mingw-w64-x86_64-vulkan-headers-1.3.207-1  mingw-w64-x86_64-vulkan-loader-1.3.207-1  mingw-w64-x86_64-winpthreads-git-9.0.0.6448.b03cbfb95-1  mingw-w64-x86_64-x264-0.161.r3039.544c61f-2  mingw-w64-x86_64-x265-3.5-1  mingw-w64-x86_64-xvidcore-1.3.7-2  mingw-w64-x86_64-zimg-3.0.3-1  mingw-w64-x86_64-zziplib-0.13.72-3  mingw-w64-x86_64-ffmpeg-4.4.1-11
Total Download Size:      0.63 MiB
Total Installed Size:  1551.40 MiB
:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-x86_64-ffms2-2.40-1-any downloading...
 mingw-w64-x86_64-libvorbis-1.3.7-1-any downloading...
 mingw-w64-x86_64-lz4-1.9.3-1-any downloading...
checking keyring...
checking package integrity...
error: failed to commit transaction (invalid or corrupted package)
error: mingw-w64-x86_64-ffms2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libvorbis: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-lz4: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-ffms2-2.40-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-libvorbis-1.3.7-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-lz4-1.9.3-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
Do you want to delete it? [Y/n]
Do you want to delete it? [Y/n]
Errors occurred, no packages were upgraded.
Update operation finished

**Comment by axcore** [comment] 2022-07-05 08:51
Duplicate of #371.

Several packages in the MSYS2 repository are broken at the moment. You can wait for them to be fixed, or you can try the workaround described [here](https://github.com/axcore/tartube/issues/371#issuecomment-1024896301).

**Closed by axcore** 2022-07-05 08:52 UTC
Labels: bug
