### ISSUE TITLE
Why does my download stop before it is finished?

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#174] opened 2020-10-19 08:38 UTC
Why does my download stop before it is finished? for Tartube.

**Comment by axcore** [comment] 2020-10-19 09:42
Does the same thing happen, when you run **youtube-dl** from the command line?

**Comment by candrapersada** [comment] 2020-10-19 09:44
yes

**Comment by axcore** [comment] 2020-10-19 09:44
If youtube-dl stops downloading something, before it is finished, then I don't know how to fix it.

**Comment by candrapersada** [comment] 2020-10-19 11:25
how to use the external downloader from the [Motrix](https://motrix.app/)

**Comment by axcore** [comment] 2020-10-19 11:30
I have never used that.

**Comment by candrapersada** [comment] 2020-10-29 01:40
how to use aria2 from [Motrix](motrix.app) or Windows?
![image](https://user-images.githubusercontent.com/36833664/97514822-406a7300-19c2-11eb-9c47-b03861e3bb3f.png)

**Comment by axcore** [comment] 2020-10-29 08:01
I don't know. I have never used the external downloader.

**Comment by candrapersada** [comment] 2020-10-29 23:53
if so how to automatically resume download when it stops?

**Comment by axcore** [comment] 2020-10-30 07:44
Have you tried [using youtube-dlc](https://github.com/blackjack4494/yt-dlc)? Maybe your download problem has been fixed there.

**Edit > System preferences... > youtube-dl > File paths**, and in the box **Use this fork of youtube-dl**, typo **youtube-dlc**

Then, in the Tartube window, click **Operations > Update youtube-dl**. (It should say **Update youtube-dlc**, that is a bug.)

**Comment by candrapersada** [comment] 2020-10-30 08:06
yes i am using youtube-dlc but it's still slow and stops all the time

**Comment by axcore** [comment] 2020-10-30 09:16
Ok, I will think about it.

**Comment by candrapersada** [comment] 2020-10-30 09:54
and how to use Parallel download for playlist?

**Comment by axcore** [comment] 2020-10-30 10:09
What do you mean, parallel download for playlist?

**Comment by candrapersada** [comment] 2020-10-30 10:23
what I mean is how about using --playlist-start 1 --playlist-end 5 for thread # 1 --playlist-start 6 --playlist-end 10 for thread # 2 and --playlist-start 11 --playlist-end 15 for thread # 3
![a](https://user-images.githubusercontent.com/36833664/97694016-9af3f400-1ad4-11eb-9877-747b5ad98374.PNG)

**Comment by axcore** [comment] 2020-10-30 12:11
There is a workaround, it is more simple:

**Edit > System preferences > Operations > Custom**
Select **In custom downloads, download each video independently of its channel or playlist**
Click the **Check all** button
When that is finished, click **Operations > Custom download all**

**Comment by candrapersada** [comment] 2020-10-30 12:16
working for Classic Mode?

**Comment by axcore** [comment] 2020-10-30 12:27
Not at the moment

**Comment by candrapersada** [comment] 2020-10-30 12:29
add for Classic Mode.

**Comment by axcore** [comment] 2020-10-30 12:30
Sorry: it doesn't work in classic mode and it can't be added

**Comment by candrapersada** [comment] 2020-10-30 12:46
Is there an alternative way to download each video independently of its playlist for classic mode

**Comment by axcore** [comment] 2020-11-10 17:04
In v2.2.118, you can restart a download, if has stalled. It works everywhere (including in the Classic Mode tab).

Click **Edit > System preferences... > Operations > Downloads**
Click the button **If a download stalls, ressart it after this many minutes**
Change the time, if you like (maybe 3 minutes is ok)

![stalltest](https://user-images.githubusercontent.com/37951926/98706332-a36ee900-2376-11eb-8dad-e8efab03b9bd.png)

If the download freezes, after 3 minutes it should restart

I have tested this artificiailly, but I cannot do a real test. Only you can tell me, if it is working or not.

**Comment by candrapersada** [comment] 2020-11-13 04:21
but why simultaneous downloads don't work for youtube playlist? from Classic Mode tab
![1](https://user-images.githubusercontent.com/36833664/99028295-ff698580-25a1-11eb-9f72-c362df052c93.PNG)

**Comment by axcore** [comment] 2020-11-13 06:39
1 playlist = 1 simultaneous download
2 playlists = 2 simultaneous downloads

If you want to download many videos in 1 playlist, simultaneously:

1. Right-click playlist, and select **Check playlist**
2. (Now Tartube knows the URL for each video)
3. **Edit > System preferences... > Operations > Custom**
4. Select **In custom downloads, download each video independently of its playlist**
5. Right-click playlist, and select "Custom download playlist"

**Comment by candrapersada** [comment] 2020-11-13 06:45
that I'm asking for Classic Mode tab

**Comment by axcore** [comment] 2020-11-13 09:04
Why do you need it?

**Comment by candrapersada** [comment] 2020-11-13 09:21
I ask to automatically resume downloads and 1 playlist = 2 simultaneous download

**Comment by axcore** [comment] 2020-11-13 09:34
Yes, I understand, but why do you need it?

youtube-dl does not support simultaneous downloads. Maybe it's possible in Tartube, but it is a lot of work. If there is a good reason, then I can do the work.

**Comment by candrapersada** [comment] 2020-11-13 09:56
so that the download continues when the first download is finished, and the next download is still ongoing,
especially if only one download stops for 10 seconds to move to the next download.

**Comment by candrapersada** [comment] 2020-11-15 08:21
I want to ask why the Edit > download options
Then click the Downloads > Playlists tab can't be accessed while the download is still running
for change start and end so you can use simultaneous downloads
start downloading playlist index 1, end downloading playlist index 5. and
start downloading playlist index 6, end downloading playlist index 10.
for use 2 playlists = 2 simultaneous downloads?

**Comment by axcore** [comment] 2020-11-15 08:37
When you click **Download all**, the download options are sent to youtube-dl immediately. After that, Tartube cannot change anything. Therefore, the **Edit > General download options...** window can't be opened.

**Comment by axcore** [comment] 2020-11-15 08:39
I will try to add **custom download** to the Classic Mode tab, but I don't promise that I will be successful.

**Comment by candrapersada** [comment] 2020-11-15 21:31
> I will try to add custom download to the Classic Mode tab, but I don't promise that I will be successful.

it should work fine using a batch link like the image below
![image](https://user-images.githubusercontent.com/36833664/99197341-84cc8000-27c4-11eb-9b4b-de172942611f.png)

**Comment by candrapersada** [comment] 2020-11-17 09:40
> In v2.2.118, you can restart a download, if has stalled. It works everywhere (including in the Classic Mode tab).
Only you can tell me, if it is working or not.

auto resume downloads not working
`ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

**Comment by axcore** [comment] 2020-11-17 11:13
Where do you see this error? In the output tab? In the errors/warnings tab? In the terminal window?

If the download stalls, do you always see this error? See the error only sometimes?

Please give me the URL, so I can test it.

**Comment by candrapersada** [comment] 2020-11-17 16:12
In the output tab and In the errors/warnings tab.

errors only occur every certain time.

URL https://www.youtube.com/watch?v=pggIK8RDp3I

**Comment by axcore** [comment] 2020-11-20 17:15
In v2.2.173 I added custom downloads to the Classic Mode tab.

![nov6](https://user-images.githubusercontent.com/37951926/99828746-4253cc00-2b53-11eb-999f-fde3da88b898.png)

If you want to bypass one video in a playlist, you can now do this:

1. Enable custom downloads in the Classic Mode tab (see picture above)
2. Click **Edit > System preferences... > Operations > Custom**
3. Select **In custom downlaods, download each video independently of its channel or playlist**
4. In the Classic Mode tab, add a URL for a channel or playlist
5. Click **Download all** to start the custom download
6. Tartube checks the channel/playlist, then downloads each video separately

If the video stalls, you can already restart it. I added a maximum number of restarts, so the download will eventually finish. **Edit > System preferences > Operations > Downloads**

![nov8](https://user-images.githubusercontent.com/37951926/99829219-e9d0fe80-2b53-11eb-8892-145e27593ec2.png)

**Comment by axcore** [comment] 2020-11-20 17:16
I cannot test your issue: I cannot make the download stall. 

If the download stalls, Tartube should restarts this, but I can't test it.

I tried this URL [https://www.youtube.com/watch?v=pggIK8RDp3I](https://www.youtube.com/watch?v=pggIK8RDp3I), but it downloads without problems.

**Comment by candrapersada** [comment] 2020-11-20 21:28
why `%(playlist)s/%(playlist_index)s` and `Autonumber` just give NA name not numbers, for custom downloads?

**Comment by axcore** [comment] 2020-11-26 15:02
> why `%(playlist)s/%(playlist_index)s` and `Autonumber` just give NA name not numbers, for custom downloads?

It is a youtube-dl problem, not a Tartube problem. I tested just youtube-dl:

`youtube-dl -o "/home/ra/Desktop/test/%(playlist)s/%(playlist_index)s" https://www.youtube.com/watch?v=tPEE9ZwTmy0&list=PLHJH2BlYG-EEBtw2y1njWpDukJSTs8Qqx`

...and I can also see NA not numbers.

**Comment by ceonelson** [comment] 2020-12-04 21:15
> If a download stalls, ressart it after this many minutes. not working
> `ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`
> and
> `ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo failed>`

That error has to do with your connection being bad. I'd never gotten it before but this morning my cable modem was down for a few hours so I tried to download some videos via my phone's 4g hotspot and they would only get 10-15% before that error happened. Wish I would have seen the auto restart option as I kept manually resuming them!

**Comment by axcore** [comment] 2020-12-05 07:23
@ceonelson, when you see that error, does Tartube's auto-restart work? @candrapersada thinks that it doesn't work for him.

**Comment by ceonelson** [comment] 2020-12-05 15:53
I tried it on my 4g hotspot but I guess there's not much congestion at 0900 on a Saturday as I didn't get that error once... I'll try again later and see if I can reproduce it.

That being said, I tried by disconnecting the wifi and got a different message:

[download] Got server HTTP error: [WinError 10054] An existing connection was forcibly closed by the remote host. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo failed>

Then tartube popped up the "download complete" dialogue. When I reconnected to the internet it didn't try to restart automatically.

How does the stalled download detection work?

**Comment by axcore** [comment] 2020-12-05 16:14
> I'll try again later and see if I can reproduce it.
If you manage to do that, the question I really need an answer to is this: is the `ERROR: unable to download video data` message visible in the terminal window? When you see one of these errors, is there any error visible in the terminal window? Or are these errors confined to Tartube's **Output** tab?

>How does the stalled download detection work?
I'm not sure it does, yet, because I can't reproduce any of these errors ;)

But, in theory, youtube-dl(c) produces output in STDOUT and STDERR. Tartube checks both of them frequently, and if it notices that nothing has happened for several minutes, it kills the youtube-dl process and starts a new one in its place. (Even when downloading a very large video, there is still STDOUT output that Tartube can read, even when it's not visible in the **Output** tab.)

**Comment by ceonelson** [comment] 2020-12-05 16:32
The error was only in Tartube's Output tab.  It would give that then Tartube would pop up the "download complete" dialog even though the video had only downloaded a few % before the WinError 10060 happened in the output tab.  The same when I disconnected the wifi - as described above and nothing logged in terminal.

**Comment by axcore** [comment] 2020-12-05 16:50
Ok, so in theory we could make Tartube restart the download if it sees one of those error messages. They are probably operating-system specific though.

**Comment by ceonelson** [comment] 2020-12-09 06:14
@axcore I tried again tonight over hotspot and the download failed after about 30%. Tartube popped up a download complete dialog:
![image](https://user-images.githubusercontent.com/16659133/101591933-07ef8900-39b3-11eb-8b3a-419fbe28c100.png)

The Errors / Warnings tab showed this:
![image](https://user-images.githubusercontent.com/16659133/101591957-150c7800-39b3-11eb-8872-84f22b562e45.png)

I had Tartube set to auto restart stalled downloads after 1 minute, but that didn't work. Might be because the download errored out rather than stalled?

Nothing is in the terminal window, but this was in the output window:
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by ceonelson** [comment] 2020-12-09 06:15
Maybe make the restart stalled option also work if it detects a "urlopen error" string? That might be cross platform vs the WinError one.

**Comment by axcore** [comment] 2020-12-09 08:32
I checked the youtube-dl code, the `Unable to download video data` part is cross-platform, but the `urlopen error` part is generated by the (MS Windows) system.

**Comment by ceonelson** [comment] 2020-12-09 09:19
I can give it a shot, will probably just download a VirtualBox image - is there a particular distro that would be best/easiest to test it on?

**Comment by ceonelson** [comment] 2020-12-11 11:30
Probably going to test this with my mac / linux buddy over Christmas (also get them setup with TarTube!) but had a thought for in the meantime. 

Are you going to parse for certain strings to determine if there was a connection error to do an auto restart? If so, if you want to write the logic for that then we can test it on the urlopen error string and then just add in the other platforms strings in a couple weeks when we can get them for you.

**Comment by axcore** [comment] 2020-12-11 11:37
v2.3.015 parses the first part of the line, "unable to download video data", because that part is generated by youtube-dl(c) itself, and should be platform-independent.

Parsing additional messages will be no problem, if you discover them.

**Comment by ceonelson** [comment] 2020-12-12 08:45
> v2.3.015 parses the first part of the line, "unable to download video data", because that part is generated by youtube-dl(c) itself, and should be platform-independent.
> 
> Parsing additional messages will be no problem, if you discover them.

Is that what the "If a download stalls due to a network problem, restart it immediately" operations -> downloads option does?

**Comment by axcore** [comment] 2020-12-12 08:57
> Is that what the "If a download stalls due to a network problem, restart it immediately" operations -> downloads option does?

Yes. I can see why that might be unclear, so I have changed the text to "If a network problem is detected, restart the download immediately"

**Comment by candrapersada** [comment] 2021-01-05 02:43
> Yes. I can see why that might be unclear, so I have changed the text to "If a network problem is detected, restart the download immediately"

Why does the automatic resume download not work and and only there is a notification that the download operation is complete but the file is still not finished like this image?
![aw](https://user-images.githubusercontent.com/36833664/103600509-29a04980-4f3a-11eb-8b8c-4870d6eb9b60.PNG)
![aww](https://user-images.githubusercontent.com/36833664/103600519-32911b00-4f3a-11eb-901f-552f0ffa96dd.PNG)

**Comment by axcore** [comment] 2021-01-05 08:09
>Why does the automatic resume download not work

I don't know, because I can't reproduce it.

>and only there is a notification that the download operation is complete but the file is still not finished like this image?

That should be impossible. I don't have an explanation for it.

**Closed** 2021-09-16 03:52 UTC
Labels: bug
