### ISSUE TITLE
Tartube does not exit correctly on Ubuntu 20.04

### ISSUE THREAD

**Issue by heurekus** [axcore/tartube#98] opened 2020-05-26 12:29 UTC
I've installed tartube on two newly installed Ubuntu 20.04 machines and face the same issue on both: It runs great but doesn't exit correctly. The GUI window goes away but the python3 task does not exit. When starting again, tartube notices that the database is still open and asks if to ignore it or not. I can kill the python3 task and restart and then everything is fine again. Until I quit tartube again.

Let me know if/how I can provide further details. Thanks!

**Comment by axcore** [comment] 2020-05-27 07:28
Tartube creates a number of threads (multiple different things happening simultaneously). At a rough guess I would say that Tartube tries to shut down these threads, and that hangs indefinitely. (The threads are shut down before the database is saved).

You could try disabling livestreams, since that code is new and not very well tested. Click **Edit > System preferences > Operations > Livestreams** and deselect **Detect livestreams announced withint this many days**.

If you're feeling adventurous, you could try adding some debug messages in the Tartube code, to find out what is causing the hanging. 

Find the mainapp.py file. (Its location on your filesystem depends on how you installed Tartube). Open it in a text editor (again, depending on the installation method, you might have to get admin privileges first).

Find the function stop_continue(). In Tartube v2.1.0 it's at line 2645.

Add this line at various places inside the function, changing the 9999 to the actual line number

`print(9999)`

So that you have something like this:

```
        # (No need to check the livestream operation here - it was stopped in
        #   the call to self.stop() )
        print(2659)
        if self.download_manager_obj:
            self.download_manager_obj.stop_download_operation()

        elif self.update_manager_obj:
            self.update_manager_obj.stop_update_operation()

        elif self.refresh_manager_obj:
            self.refresh_manager_obj.stop_refresh_operation()

        elif self.info_manager_obj:
            self.info_manager_obj.stop_info_operation()

        elif self.tidy_manager_obj:
            self.tidy_manager_obj.stop_tidy_operation()

        # Stop the GObject timers immediately. So this action is not repeated
        #   in the standard call to self.do_shutdown, reset the IVs
        print(2677)
        if self.script_slow_timer_id:
            GObject.source_remove(self.script_slow_timer_id)
            self.script_slow_timer_id = None

        if self.script_fast_timer_id:
            GObject.source_remove(self.script_fast_timer_id)
            self.script_fast_timer_id = None

        if self.dl_timer_id:
            GObject.source_remove(self.dl_timer_id)
            self.dl_timer_id = None

        if self.update_timer_id:
            GObject.source_remove(self.update_timer_id)
            self.update_timer_id = None

        if self.refresh_timer_id:
            GObject.source_remove(self.refresh_timer_id)
            self.refresh_timer_id = None

        if self.info_timer_id:
            GObject.source_remove(self.info_timer_id)
            self.info_timer_id = None

        if self.tidy_timer_id:
            GObject.source_remove(self.tidy_timer_id)
            self.tidy_timer_id = None

        # Empty any temporary folders from the database (if allowed; those
        #   temporary folders are always deleted when Tartube starts)
        # Otherwise, open the temporary folders on the desktop, if allowd
        print(2709)
        if self.delete_on_shutdown_flag:
            self.delete_temp_folders()
        elif self.open_temp_on_desktop_flag:
            self.open_temp_folders()

        # Delete Tartube's temporary folder from the filesystem
        print(2716)
        if os.path.isdir(self.temp_dir):
            shutil.rmtree(self.temp_dir)

        # Save the config and database files for the final time, and release
        #   the database lockfile
        print(2722)
        self.save_config()
        self.save_db()
        self.remove_db_lock_file()

        # I'm outta here!
        self.quit()


```

**Comment by heurekus** [comment] 2020-05-27 15:05
Thanks! I tried switching-off the live function but the issue persists. 

Then I inserted the print statements as described. Looks like the function never gets called at all. Even a print statement before the first statement never makes its way to the screen. 

Just to see that I'm not doing something stupid, I put a print statement into __init__. This one prints just fine. 

So I guess we need some further statements higher up in the code. Any good places for that (function names are good enough, no need to give me the line numbers).

**Comment by axcore** [comment] 2020-05-27 15:22
OK, then we can turn on debug messages generally.

Near the top of **mainapp.py**, find these lines:

`# Debugging flag (calls utils.debug_time at the start of every function)
DEBUG_FUNC_FLAG = False
# ...(but don't call utils.debug_time from the timer functions such as
#   self.script_slow_timer_callback() )
DEBUG_NO_TIMER_FUNC_FLAG = False`

And change the values to True (must be capitalised):

`# Debugging flag (calls utils.debug_time at the start of every function)
DEBUG_FUNC_FLAG = True
# ...(but don't call utils.debug_time from the timer functions such as
#   self.script_slow_timer_callback() )
DEBUG_NO_TIMER_FUNC_FLAG = True`

Do the same thing to the two flags near the top of **mainwin.py**, and the single flag near the top of **downloads.py**.

You should see millions of debug messages in the terminal window, as Tartube runs.

**Comment by heurekus** [comment] 2020-05-27 15:45
Done, here are the last debug lines after just opening/closing tartube. Never returns to the shell.
```

2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:02 mwn 6448 video_index_render_text
2020-05-27 17:44:05 mwn 12937 on_delete_event
2020-05-27 17:44:05 mwn 2535 toggle_visibility

```

**Comment by axcore** [comment] 2020-05-27 16:11
Tartube is closing to the system tray, not closing the application itself. On Linux Mint I see this:

![tray](https://user-images.githubusercontent.com/37951926/83044966-d6c5f180-a03c-11ea-9484-2afed453573c.png)

I haven't tried Ubuntu 20.04 yet; perhaps it doesn't have a system tray (or perhaps the Tartube icon isn't visible there). You can tell me which is more likely.

Workarounds are:

1. Close from the menu, **File > Quit**
2. Click the large Quit button in the toolbar near the top of the main window
3. Tell Tartube not to close to the tray. Click **Edit > System preferences... > Windows > System tray ** and deselect **Close to the tray, rather than closing the application**

**Comment by heurekus** [comment] 2020-05-27 16:28
Yay, the workarounds are working!

Since I can disable the tray behavior in the settings that fixes it for me for the scenario that I install it on my wife's computer who will press the X close button instead of going to the menu. Excellent!

I had a look and Ubuntu 20.04 does not have a "tray" icon when I close tartube with the X button. See screenshot. Other 'tray' icons, e.g. of Remmina show up next to the network icon at the upper right corner.

So perhaps it would be a good idea to disable "minimize" to tray by default after installation and allow users to activate it in the preferences (i.e. opposite from today's behavior)?

In any case, thanks very very much for looking into this, one issue less that stops me from upgrading others to Ubuntu 20.04 :-)

![Screenshot from 2020-05-27 18-22-59](https://user-images.githubusercontent.com/47881430/83046671-a20b6780-a047-11ea-9352-482d5675720d.png)

**Comment by axcore** [comment] 2020-05-27 16:53
So, before disabling the setting, the Tartube icon wasn't visible in the top-right corner of your desktop? If not, I will have to think about disabling it by default.

**Comment by axcore** [comment] 2020-05-27 16:54
>So perhaps it would be a good idea to disable "minimize" to tray by default after installation and allow users to activate it in the preferences (i.e. opposite from today's behavior)?

Yes, I will have to think about that.

**Comment by heurekus** [comment] 2020-05-27 19:05
One more thing: 

It seems the setting "Close to the tray, rather than closing application" is not saved into the preferences file when exiting by clicking on the 'X' close window button . I noticed because it worked once but when I opened/closed/opened tartube again it again didn't quit correctly and the checkbox was marked again. 

When I exit Tartube via the File - Quit menu, the preference is correctly saved into ~/.config/tartube/settings.json

Should be easy to find.

**Comment by axcore** [comment] 2020-05-27 19:50
Confirmed. I'll fix that.

**Comment by axcore** [comment] 2020-05-29 07:45
v2.1.020 disables closing to the system tray by default (only affects new installations). The file save issue is also fixed.

I can't produce new installers until next month, but the fixed source code has been uploaded to Github.

**Closed by axcore** 2020-05-29 07:45 UTC
Labels: bug
