### ISSUE TITLE
Don't download thumbnail

### ISSUE THREAD

**Issue by ILove07Gold** [axcore/tartube#376] opened 2022-02-02 03:44 UTC
Is there an option to not download the thumbnail? i dont need it. Using the classic mode, and every time i have to delete the thumbnail file that is downloaded.

**Comment by axcore** [comment] 2022-02-02 07:47
Edit > General download options > Files > Write files
Deselect **Write the video's thumbnail to the same folder**

Alternatively, in the **Keep files** tab, deselect **Keep the thumbnail file after the download has finished**

**Comment by PatrickL546** [comment] 2022-03-13 13:10
Might be a bug because "Keep the thumbnail file after the download has finished" absolutely does nothing to me. Thumbnail is kept even if it's not checked
![image](https://user-images.githubusercontent.com/75874561/158060845-ee00a66d-bd9c-4ad1-be30-8b4a09fb798a.png)

**Comment by axcore** [comment] 2022-03-13 14:46
@PatrickL546, make sure that the download options you're modifying apply to the videos you are downloading.

Click **Edit > System preferences... > Options > Download options**

In the list there should be at least two items, **general** and **classic**, looking like this:
![options](https://user-images.githubusercontent.com/37951926/158065048-84ed072f-823a-4a6e-802d-0cef3d1323ef.png)

If your window doesn't look exactly like that, take a screenshot and show me.

**Comment by PatrickL546** [comment] 2022-03-14 09:58
My system settings is exactly like that. I edited the generals download options and untick the settings and downloaded a video. It's still there.
![image](https://user-images.githubusercontent.com/75874561/158148819-06a9f0f4-7887-4b77-95f1-871de666a5b6.png)

**Comment by axcore** [comment] 2022-03-14 11:27
What happens when you select everything in the **Keep files** tab?

By way of an explanation: yt-dlp lets you choose which files to download. Tartube wants to read some of those files, so you can let Tartube download them and then discard them (or keep them, if you want to keep them).

**Comment by PatrickL546** [comment] 2022-03-14 16:39
![image](https://user-images.githubusercontent.com/75874561/158219092-b888b89c-cd2f-4365-a842-490a36f90297.png)

**Comment by axcore** [comment] 2022-03-14 17:50
You're looking at an original thumbnail in .webp format. Gtk can't display .webp images (hardly anything can), so FFmpeg converts it into something that is visible (.png). 

For some reason the original isn't deleted straight after conversion. I will look into that, just as soon as you give me the link to the video  you're trying to download there.

**Comment by PatrickL546** [comment] 2022-03-14 18:55
Here's the vid: https://www.youtube.com/watch?v=aSgnmiVSsAI
Just a random video that was in my home page. I checked already that this is happening on other youtube videos

**Comment by axcore** [comment] 2022-06-08 08:35
Sorry for the delay in responding.

I can't reproduce your problem, despite several attempts. If you are still here, you can try download the video again, then when it fails to delete the image file, take a screenshot of the yellow text at the top of the Output tab so I can make sure I am replicating your exact setup.

**Comment by PatrickL546** [comment] 2022-06-08 09:14
I've updated to the newest version released 8 days ago, updated yt-dlp. It's not downloading the thumbnail anymore. Seems to be fixed somehow.

**Comment by axcore** [comment] 2022-06-08 11:04
Ok, I have tested an identical setup on both Linux and MS Windows, but I still can't reproduce your problem.

![samesetup](https://user-images.githubusercontent.com/37951926/172600625-d049c804-39b9-44b5-87db-0fa578dba839.png)

The relevant code is in the `utils.py` file, in the `handle_files_after_download()` function. 

`    # Thumbnail file
    if dummy_obj:
        thumb_path = find_thumbnail(app_obj, dummy_obj)
    else:
        thumb_path = find_thumbnail_from_filename(app_obj, dir_path, filename)

    if thumb_path and not options_obj.options_dict['keep_thumbnail']:

        new_path = convert_path_to_temp(app_obj, thumb_path)

        if os.path.isfile(thumb_path):
            if not os.path.isfile(new_path):
                app_obj.move_file_or_directory(thumb_path, new_path)
            else:
                app_obj.remove_file(thumb_path)

    elif thumb_path \
    and not os.path.isfile(thumb_path) \
    and options_obj.options_dict['move_thumbnail'] \
    and dummy_obj:

        move_thumbnail_to_subdir(app_obj, dummy_obj)`

If you feel like burrowing around inside the code, you could add some debug messages, like so:

`    # Thumbnail file
    if dummy_obj:
        thumb_path = find_thumbnail(app_obj, dummy_obj)
    else:
        thumb_path = find_thumbnail_from_filename(app_obj, dir_path, filename)

    print("thumb_path")
    print(thumb_path)
    
    if thumb_path and not options_obj.options_dict['keep_thumbnail']:

        new_path = convert_path_to_temp(app_obj, thumb_path)
        print("new_path")
        print(new_path)

        if os.path.isfile(thumb_path):
            if not os.path.isfile(new_path):
                print("move_file_or_directory")
                app_obj.move_file_or_directory(thumb_path, new_path)
            else:
                print("remove_file")
                app_obj.remove_file(thumb_path)

    elif thumb_path \
    and not os.path.isfile(thumb_path) \
    and options_obj.options_dict['move_thumbnail'] \
    and dummy_obj:

        print("move_thumbnail_to_subdir")
        move_thumbnail_to_subdir(app_obj, dummy_obj)`

**Comment by axcore** [comment] 2022-06-08 11:08
The relevant code is in the **../tartube/utils.py** file, in the **handle_files_after_download()** function. 


`    if thumb_path and not options_obj.options_dict['keep_thumbnail']:

        new_path = convert_path_to_temp(app_obj, thumb_path)

        if os.path.isfile(thumb_path):
            if not os.path.isfile(new_path):
                app_obj.move_file_or_directory(thumb_path, new_path)
            else:
                app_obj.remove_file(thumb_path)

    elif thumb_path \
    and not os.path.isfile(thumb_path) \
    and options_obj.options_dict['move_thumbnail'] \
    and dummy_obj:

        move_thumbnail_to_subdir(app_obj, dummy_obj)`


If you feel like burrowing around inside the code, you could add some debug messages, like so:


`
    print("thumb_path")
    print(thumb_path)
    
    if thumb_path and not options_obj.options_dict['keep_thumbnail']:

        new_path = convert_path_to_temp(app_obj, thumb_path)
        print("new_path")
        print(new_path)

        if os.path.isfile(thumb_path):
            if not os.path.isfile(new_path):
                print("move_file_or_directory")
                app_obj.move_file_or_directory(thumb_path, new_path)
            else:
                print("remove_file")
                app_obj.remove_file(thumb_path)

    elif thumb_path \
    and not os.path.isfile(thumb_path) \
    and options_obj.options_dict['move_thumbnail'] \
    and dummy_obj:

        print("move_thumbnail_to_subdir")
        move_thumbnail_to_subdir(app_obj, dummy_obj)
`

**Comment by axcore** [comment] 2022-06-08 18:52
Yes, I tested it about 20 times today. The .webp appears during the download, but is always removed at the end, leaving just the video file.

**Comment by axcore** [comment] 2022-06-08 18:57
You have double- and triple-checked that you are using the download options for the Classic Mode tab, right?

(In that tab, click the menu icon in the top-right, and select **Edit download options**. Alternatively, from the main menu, click **Edit > System preferences ... > Options**, and see which set of download options is marked for use with **Classic Mode**.)

**Comment by PatrickL546** [comment] 2022-06-09 04:24
Mystery kinda solved? Went into tartube install location and deleted settings.json. I do the same thing i've been doing and the thumbnail is removed somehow. Checked 

> (In that tab, click the menu icon in the top-right, and select Edit download options. Alternatively, from the main menu, click Edit > System preferences ... > Options, and see which set of download options is marked for use with Classic Mode.)

that options and it's the same with new and old settings.json.

Somehow my old settings.json is causing it.

**Comment by axcore** [comment] 2022-06-11 06:53
I tested both settings.json files with the same video. The result is the same: the images are deleted, leaving only the videos.
![test1](https://user-images.githubusercontent.com/37951926/173177096-33fbdf4b-8df8-42e9-b844-0724cdd0485a.png)
![test2](https://user-images.githubusercontent.com/37951926/173177098-b6b5ab86-7f35-4817-9c8e-0ad303fbe928.png)

**Comment by PatrickL546** [comment] 2022-06-11 07:52
I'll just record what happens

**Comment by PatrickL546** [comment] 2022-06-11 10:44
I used the exact same settings here except I added the download paths.
As you can see at the end, the normal download with default settings.json deleted the thumbnail but the classic download doesn't delete it.

old settings.json - Doesn't delete when using normal download and classic.
default settings.json - Deletes when using normal download but not when using classic.


https://user-images.githubusercontent.com/75874561/173184514-5312ac6b-0664-49f2-894e-dfe9f0e4f31c.mp4

**Comment by axcore** [comment] 2022-11-25 06:05
The code handling deletion of unwanted thumbnails has been rewritten for the v2.4.165 release. I was never able to reproduce your problem, but whatever the cause was, that code doesn't exist any more.

Since you could repair your setup by replacing the settings file, I'll go ahead and close this issue, but feel free to open a new one if the same problem occurs again.

**Closed** 2022-11-25 06:05 UTC
Labels: question
