### ISSUE TITLE
Cannot check/download channels/playlists on YouTube

### ISSUE THREAD

**Issue by Galeonz** [axcore/tartube#192] opened 2020-11-11 05:14 UTC
I'm running version 2.2.007 on windows 10. 
So I installed Tartube for the first time 2 days ago and it worked just fine, I was able to check channels.
I don't know exactly what happened but suddenly when I click "Check Channel" it just sits there for 5 seconds and returns the "Download Operation complete" notification but nothing actually happens, I don't see any videos, the folder is completely empty, no thumbnails downloaded.
Also if I right click Show > Channel Properties it's not detecting the RSS Feed link automatically.

The Output tab doesn't show any clues of what is happening, just the initial command.
The Progress tab shows status as "Finished" after trying to check the channel.
Errors/Warnings doesn't show anything.

![check3](https://user-images.githubusercontent.com/12306198/98771369-0e461180-23c3-11eb-8760-8609314dd2e2.jpg)
![check1](https://user-images.githubusercontent.com/12306198/98770878-f8841c80-23c1-11eb-89b2-f953cb8fb701.jpg)
![check2](https://user-images.githubusercontent.com/12306198/98770904-033eb180-23c2-11eb-81d3-9b90671fad01.jpg)

It seems to happen only on youtube channels, I'm still able to check Bitchute channels just fine. 
Downloading single youtube videos still works.

Things I tried and had no success in solving the problem:
Uninstalled Tartube 2 times (nothing left on Appdata folder), reinstalled Youtube-dl/FFmpeg when Tartube asked me, tried switching to the Youtube-DLC fork and updating it.

**Comment by Indochild56** [comment] 2020-11-11 06:06
same thing's happened to me. i've even tried updating the files with the code on here, and installed on another computer.

**Comment by axcore** [comment] 2020-11-11 07:19
YouTube have just changed their codebase, so youtube-dl is broken. It should be fixed in a few days. Use **Operations > Updated youtube-dl** and wait for the new release.

**Comment by Galeonz** [comment] 2020-11-11 07:27
> YouTube have just changed their codebase, so youtube-dl is broken. It should be fixed in a few days. Use **Operations > Updated youtube-dl** and wait for the new release.

Oh, good to know it's affecting more people and not just me. 
Gonna wait for the youtube-dl fix then, Thanks. 😄

**Comment by candrapersada** [comment] 2020-11-11 23:39
why name folder broken `%(playlist)s/` and `%(playlist_title)s/`?

**Comment by Galeonz** [comment] 2020-11-12 01:49
For those with the same problem, a new version of youtube-dl is out (v2020.11.12) and it fixed the problem for me.
"Check Channel" is working as intended again.

**Comment by thansk** [comment] 2020-11-13 01:47
Updating youtube-dl works, maybe issue should be closed but still pinned.

**Comment by axcore** [comment] 2020-11-13 06:19
When youtube-dl 'checks' a channel, I am seeing it check the same video three times. It's not fixed yet :)

**Comment by Anticancer123** [comment] 2020-11-13 08:09
I got past this step this but only one video downloaded

**Comment by axcore** [comment] 2020-11-13 08:58
youtube-dlc seems to be working better, so you should try that.

**Comment by Anticancer123** [comment] 2020-11-14 06:08
Can I get qa link to download it .It keep closing everytime I click the exe file

**Comment by axcore** [comment] 2020-11-14 07:40
I don't know what a qa link is, but I think you want [this one](https://github.com/axcore/tartube#625-using-youtube-dl-forks).

**Comment by Anticancer123** [comment] 2020-11-15 07:44
I meant a link sorry,Tartrube seems to be working now at least for the channel Im downloading is there a way to download the oldest videos instead of the newest ones first?

**Comment by axcore** [comment] 2020-11-15 07:48
**Edit > General download options**
If the **Show advanced download options** button is visible, click it
Then click the **Downloads > Playlists** tab
Select **Download playlist in reverse order**

**Comment by Anticancer123** [comment] 2020-11-15 09:03
Ok is there any way to to remove the dates or set it to the time I  downloaded it? And are signed video and video's that are age restricted automatically downloaded?

**Comment by axcore** [comment] 2020-11-15 09:14
>Ok is there any way to to remove the dates or set it to the time I downloaded it?

No, not at the moment

>And are signed video and video's that are age restricted automatically downloaded?
I'm not sure what you mean by signed videos. But for restricted videos, it depends. There are many categories of 'age-restricted' video that YouTube, and those categories are a secret. We don't know what they are. youtube-dl can either check/download them, or it can't.

Age-restricted videos can often be downloaded from HookTube and/or Invidious, if they can't be downloaded from YouTube directly. [See here](https://github.com/axcore/tartube#613-custom-downloads) for more information.

**Comment by Anticancer123** [comment] 2020-11-15 09:52
Sorry I meant videos that required one to signed in first

**Comment by Anticancer123** [comment] 2020-11-15 10:00
And is there an option for Facebook videos?

**Comment by axcore** [comment] 2020-11-15 10:51
I don't know, I don't have a facebook account so I have never tried signing in with it.

**Comment by heywolf15** [comment] 2020-11-16 01:05
https://github.com/blackjack4494/yt-dlc/issues/148#issuecomment-725915379

using --rm-cache-dir --no-cache-dir params in your command. This works for me

**Comment by heywolf15** [comment] 2020-11-16 18:44
I wonder why no one make an issue about that in yt-dl

**Comment by heywolf15** [comment] 2020-11-18 16:34
I think it's Tartube problem, cus even latest yt-dl didn't fix it

I'm using the latest code cus when I downgrade it to the latest release the database has different version.
Trying making a new database just to test it and it works.
Then I import the old database and move all the videos.
It just works.

**Comment by axcore** [comment] 2020-11-18 16:52
@heywolf15 there are several issues mentioned on this page, which one do you think is the Tartube problem?

Can you give me a channel/playlist URL that I can test, and reproduce the problem?

**Comment by Anticancer123** [comment] 2020-11-22 03:04
@axcore Why are the videos downloading's only 1 at a time despite the maxmunim download increased and why the speed low despite the increase there as well.

**Comment by axcore** [comment] 2020-11-22 09:25
>Why are the videos downloading's only 1 at a time 

If you download a channel or playlist, youtube-dl downloads one video at a time. If you want to download multiple videos simultaneously, use a [custom download](https://github.com/axcore/tartube#613-custom-downloads).

>despite the maxmunim download increased and why the speed low despite the increase there as well.

When you start downloading the channel or playlist, the **Max downloads** and **D/L speed** values are passed to youtube-dl. It is not possible to tell youtube-dl to change the values, once it has started.

**Comment by axcore** [comment] 2020-11-26 17:19
> Ok is there any way to to remove the dates or set it to the time I downloaded it?

@Anticancer123, v2.2.198 adds the ability to sort videos by download time. 

In the **Videos** tab, in the bottom right, there's an arrow icon. Click it to reveal some more icons, including an option to sort by download time. The date shown with each video will then be the download time.

There are one or two problems with sorting in general that still need to be ironed it, but it should be working in general.

**Comment by Anticancer123** [comment] 2020-11-28 08:43
> I don't know, I don't have a Facebook account so I have never tried signing in with it.

I was meaning can it5 download Facebook videos and what of patron vids as well?

**Comment by axcore** [comment] 2020-11-28 08:58
> I was meaning can it5 download Facebook videos and what of patron vids as well?

Same answer - I have never used Facebook so I don't know. I checked the youtube-dl code, there is an [extractor for Facebook](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/facebook.py), so it might work.

There is also an [extractor for Patreon](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/patreon.py), so that might work too.

**Comment by axcore** [comment] 2020-12-01 09:52
The original problem seems to be resolved. If anyone experiences any related problems, feel free to open a new issue.

**Closed by axcore** 2020-12-01 09:52 UTC
Labels: bug
